### ISSUE TITLE
When importing a generated plugin and using bin/run "Cannot use import statement outside a module" 

### ISSUE THREAD

**Issue by Tuaev** [oclif/oclif#1000]
After running generating 2 CLI's and trying to add one to the other as a dependency and in the plugins array I get the error `Cannot use import statement outside a module`

They work fine if I'm running the commands with bin/dev but once I build the CLI I get that error. The 2 CLI's are oclif generated but the default hello command and the other renamed to something else. 

The tsconfig.json are untouched and only once package.json is edited to add the other cli as a dependency and in the plugins array.

Anyone come across this or know how to add one cli's commands to the other as a plugin? I had no issues with this prior to v2 of oclif.

**Comment by mdonnalley** [comment]
@Tuaev Thanks for reporting this.

I believe this is an issue with mixing `bin/dev` with a a dependency that's been added via `yarn add file`. I'm not exactly sure what's going on there so I'll need to dig in deeper. 

However, there are a couple of workarounds that should unblock you:

1. Use `bin/run`. For this, you'll need to `yarn build` in each plugin before running it so that you get all your latest changes
2. `yarn link` the plugin and continue to use bin/dev, e.g.

```
cd plugin-b
yarn link
cd ../plugin-a
yarn link plugin-b
```
