### ISSUE TITLE
Input required and not supplied: token

### ISSUE THREAD

**Issue by dmatora** [oclif/oclif#1059]
When I generate new cli using `npx oclif generate mynewcli` and push it to GitHub repo, GitHub actions fail with
`Input required and not supplied: token` error
debug run shows
```
##[debug]Evaluating: secrets.SVC_CLI_BOT_GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'SVC_CLI_BOT_GITHUB_TOKEN'
##[debug]=> null
```
Adding SVC_CLI_BOT_GITHUB_TOKEN to repo secrets doesn't help

**Comment by nya1** [comment]
Hello,
The issue is that the default template is using the github action located here [oclif/github-workflows](https://github.com/oclif/github-workflows/tree/main/.github) apparently secrets cannot be "shared" (inherited) from different orgs, I resolved it by cloning the oclif/github-workflows repository (note: a simple fork doesn't work) and changing the references from "oclif" to my cloned repository, a similar issue was created here: https://github.com/salesforcecli/github-workflows/issues/22

**Comment by demarchenac** [comment]
> When I generate new cli using `npx oclif generate mynewcli` and push it to GitHub repo, GitHub actions fail with `Input required and not supplied: token` error debug run shows
> 
> ```
> ##[debug]Evaluating: secrets.SVC_CLI_BOT_GITHUB_TOKEN
> ##[debug]Evaluating Index:
> ##[debug]..Evaluating secrets:
> ##[debug]..=> Object
> ##[debug]..Evaluating String:
> ##[debug]..=> 'SVC_CLI_BOT_GITHUB_TOKEN'
> ##[debug]=> null
> ```
> 
> Adding SVC_CLI_BOT_GITHUB_TOKEN to repo secrets doesn't help

Did you manage to solve this issue?

**Comment by mdonnalley** [comment]
Closing this since the templates now come with more generic github actions
