### ISSUE TITLE
Make it easy to install a package globally and locally

### ISSUE THREAD

**Issue by ianwremmel** [oclif/oclif#109]
This might be a request for an optional feature, or possibly something that can be done with a hook or plugin without needing to be in oclif directly. 

I've got a cli that *should* be installed a dev dependency because it'll be installed in CI environments, but works best if it's installed globally (it's a swiss army knife of sorts, so it's ideal if it's on the PATH). 

Ideally, a globally installed cli would check if the current project has installed a version of that cli. If so, it should delegate to the version installed in the project rather than the globally installed version. Further, this logic should be available from a folder in a given project, not just the root. Ideally, it would work in monorepos so, discovering a package.json wouldn't cause it to stop searching upward from the current directory. `mycli --version` should print both the local and globally installed versions (and possibly their paths). 

I can see arguments both ways on whether this should be a feature of oclif. I've got [a hack](https://github.com/ianwremmel/clark/blob/master/bin/run) in place that seems to work, but I feel like it could be improved with a better understanding of how oclif loads commands. From that point of view, *maybe* this is really a documentation issue. On the other hand, I can see this as a pretty generic need that's hard to test, so making it a feature of oclif (or something in the `@oclif` namespace) might save a lot of folks a lot of trouble (or, better, by making this easy, a lot more projects might implement this behavior for free).

**Comment by jdxcode** [comment]
This is doable as a plugin—though it'd be a bit of a strange one. You would have an init hook in the plugin that would proxy over to the locally installed CLI. I'm not sure I would load it though, it'd be safer across versions to use child_process to run the bin. That way if you ever wanted to migrate away from oclif or oclif internals changed significantly in a major release it would continue to work. You don't have to know about the internals that way either.

As far as the version command, that's a bit more difficult but still doable. You'd have to have a custom main multi class that would override the behavior of the version flags. To make that easier, I could add a version hook to listen to so instead it would just be a matter of listening to the version.

In terms of fetching the version, I would set an environment variable when launching the dev CLI like `CLARK_PARENT_VERSION=1.0.0`.

Alternatively, you could just use `npx`. It's made to solve this problem though I don't know how well it would work in a lerna setup.

Right now this all seems pretty complex though. I wouldn't recommend any kind of automatic switching because I think it would be surprising to the end-user. I understand the issue though. What I do in this case is install CLIs globally but lock down the major version in CI environments like this:

```
yarn global add mycli@2
mycli foobar
```

But you could also use npx:

```
npx mycli@2 foobar
```

That way you retain some control over the version of the CLI but don't need to execute it under node_modules. It's not a perfect solution but it's the simplest and best pattern I've seen for node CLIs.

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this issue is still valid, reopen it. Thanks!
