### ISSUE TITLE
How to implement sub commands in oclif?

### ISSUE THREAD

**Issue by xyNNN** [oclif/oclif#113]
Hey folks,

Currently I'm wondering how I can implement sub commands in oclif. I know that oclif can handle single cli and multi cli commands, but I need one more sub command layer like the following.

`bin/run cli project list` or
`bin/run cli project create`
`bin/run cli project delete`

How do you achieve this?

Thanks in advance!

**Comment by xyNNN** [comment]
Okay, thanks!

**Comment by danihodovic** [comment]
Dankeschön Stephan!

Will oclif allow us to generate topics using the oclif cli in the future, similar to how single and multi commands are easily generated?

E.g
```
$ npx oclif topic dani:great dani:best
```

**Comment by jdxcode** [comment]
topics are just subdirectories that contain commands so there is no need to generate them

**Comment by samuela** [comment]
It would be nice to get more docs on this. For example, how do we control the "documentation" string for the parent command? Currently oclif just appropriates the description of a subcommand which doesn't seem quite right.

**Comment by ratbeard** [comment]
https://oclif.io/docs/topics mentions how you can set the description text.

(I stumbled here because I'm looking if theres a way to specify this config in a standalone file, not package.json)

**Comment by magicdawn** [comment]
yargs support `git` style subcommands. 

e.g
```
git remote add/remove/set-url
```

**Comment by parkerhutchinson** [comment]
Just in case anyone comes across this wondering how do you perform something that is pretty standard in most CLIs these days. You can sort of hack this to make it work for subcommands using arguments. if you set an general argument like "subcommand": 

```
static args = [
  {
    name: 'subcommand',
  },
]
```

then in your run() you check to see what the value of the subcommand is: 

```
if (args.subcommand === 'custom-subcommand') {
  console.log(`${args.subcommand} ${flags.space}`);
}
```

on the command line this would look like `./run myClI myCommand custom-subcommand --space=hello world`

This works because args you pass get set at whatever position they are run at with whatever value you set. if you were to log args in the run you'd get `{'subcommand': 'custom-subcommand'}`.  Some of you may be wondering "ok so how do I pass values to the sub command?". Well you can do that either with a global flag like above or you create another arg like `subcommandValue`  and use the positional argument as the value instead like: 

```
./run myCLI myCommand custom-subcommand "hello world" 
```

in the code it would look something like: 

```

static args = [
  {
    name: 'subcommand',
  },
  {
    name: 'subcommandValue'
  }
]

if (args.subcommand === 'custom-subcommand') {
  console.log(`${args.subcommand} ${args.subcommandValue}`);
}
```
