### ISSUE TITLE
internal plugin distribution

### ISSUE THREAD

**Issue by jdxcode** [oclif/oclif#114]
currently there isn't a great way to distribute internal oclif plugins (those not on the public npm registry). You can specify a registry for a CLI but this is global and doesn't allow the CLI _end-users_ a way to change the registry just for themselves.

We should support adding plugins from git, tarballs, and potentially a way to use multiple registries.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
