### ISSUE TITLE
Cannot find module globby when running CLI

### ISSUE THREAD

**Issue by BuvSethia** [oclif/oclif#132]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Whenever I run a command on CLI built using `oclif`, I get the following error:
```
(node:8716) [MODULE_NOT_FOUND] Error Plugin: mycli: Cannot find module 'globby'
module: @oclif/config@1.6.33
task: not loading commands, globby not found
plugin: mycli
root: /Users/sumbhavsethia/.nvm/versions/node/v8.11.1/lib/node_modules/mycli
See more details with DEBUG=*
```
Installing `globby` globally resolves the issue

What is the expected behavior?
------------------------------
I should not have to install `globby` globally to be able to run the CLI. It should be installed as a dependency of `oclif`

More information
-----------------
Node version: 8.11.1
oclif version: 1.4.33

package.json:
```
"dependencies": {
    "@oclif/command": "^1.4.33",
    "@oclif/config": "^1.6.33",
    "@oclif/plugin-help": "^1.2.11",
    "bluebird": "^3.5.1",
    "bluebird-retry": "^0.11.0",
    "chalk": "^2.3.2",
    "command-exists": "^1.2.2",
    "execa": "^0.10.0",
    "hostile": "^1.3.1",
    "inquirer": "^5.2.0",
    "inquirer-path": "^1.0.0-beta5",
    "joi": "^13.1.2",
    "latest-version": "^3.1.0",
    "lodash": "^4.17.5",
    "ora": "^2.0.0",
    "pg": "^7.4.1",
    "portscanner": "^2.1.1",
    "request": "^2.85.0",
    "request-promise": "^4.2.2",
    "semver": "^5.5.0",
    "ssh-config": "^1.1.3",
    "sshpk": "^1.14.1",
    "sudo-prompt": "^8.2.0",
    "table": "^4.0.3",
    "tmp-promise": "^1.0.4",
    "wait-port": "^0.2.2"
},
"oclif": {
    "commands": "./src/commands",
    "bin": "mybin",
    "plugins": [
      "@oclif/plugin-help"
    ],
    "topics": {
      "atopic": {
        "description": "Manages atopic"
      }
    }
},
```

**Comment by jdxcode** [comment]
Globby is not required if the manifest file is found. Likely the issue is the `oclif.manifest.json` file is not being included in the CLI.

**Comment by BuvSethia** [comment]
Sorry, forgot to include that portion of `package.json`. It is being included.
```
"files": [
    ".oclif.manifest.json",
    "/bin",
    "/src"
],
```

**Comment by jdxcode** [comment]
[you also need something like this](https://github.com/oclif/example-multi-ts/blob/master/package.json#L55) in the scripts section for it to create the manifest

**Comment by jdxcode** [comment]
also please verify if the file is in fact included in the package

**Comment by BuvSethia** [comment]
Looks like it's not getting included in the package. Not sure why though. Here are the scripts being used to publish:
```
"scripts": {
    "clean": "rm -f .oclif.manifest.json",
    "lint": "eslint .",
    "postpublish": "npm run clean",
    "posttest": "npm run lint",
    "prepack": "oclif-dev manifest", *Duplicating what prepublishOnly is doing, trying whatever I could
    "prepublishOnly": "oclif-dev manifest",
    "preversion": "npm run clean",
    "version": "oclif-dev readme && git add README.md"
  }
```

**Comment by BuvSethia** [comment]
Bump

**Comment by DullReferenceException** [comment]
@BuvSethia: just had the same problem. The file that `oclif-dev manifest` produces for us is `oclif.manifest.json` (without the `.` prefix). Adding _that_ to our files (and fixing the clean script) seems to work for me (just had the same issue). Do you maybe just have a typo with that leading `.`?

**Comment by mmcc** [comment]
I'm confused as to what the solution is here, and (at least in my experience), this has made for a pretty frustrating onboarding experience. If I follow the readme and install oclif, then generate a new cli, then try to run `--version`, I get this error. I have no oclif manifest in the generated project directory, and there are 0 instances of "manifest" in the readme. Globally installing `globby` doesn't help, and adding it to the generated project simply gives a new error:

```
(node:60043) [MODULE_NOT_FOUND] Error Plugin: mux-cli: Cannot find module '/Users/mmcc/Projects/oclif-test/cli/src/commands/hello'
module: @oclif/config@1.10.4
task: toCached
plugin: oclif-test
root: /Users/mmcc/Projects/oclif-test/cli
See more details with DEBUG=*
oclif-test/0.0.0 darwin-x64 node-v9.11.1
```

**Comment by rwoody** [comment]
@mmcc The `-b` error is, I believe, due to an older version of TS being used to compile. The same thing would happen to me when I tried to use 2.9.2 (same version as other modules are using) instead of 3.2.2.

I had a problem after generating a new multi CLI project. `globby` is listed in devDependencies in those projects (multi TS/JS), but it is a runtime dependency:

```
(node:8311) [MODULE_NOT_FOUND] Error Plugin: @myproject/cli: Cannot find module 'globby'
module: @oclif/config@1.12.0
task: not loading commands, globby not found
plugin: @myproject/cli
root: /Users/me/.nvm/versions/node/v10.13.0/lib/node_modules/@myproject/cli
See more details with DEBUG=*
@apc-ng/devkit/6.5.0-pr-5838.10 darwin-x64 node-v10.13.0
```

**Comment by jdxcode** [comment]
It is not a runtime dependency. This only happens if the manifest does not exist in the package

**Comment by jdxcode** [comment]
There must be a better way of handing this. The trouble is oclif has 2 modes of operating, either in dev or in prod (essentially). In dev it is much slower and uses globby to pull down all the files to find out which commands exist (among other slow behaviors).

This is nice in dev mode as you can just add a file to the command directory and it immediately exists. In prod mode (when you publish the package) we build a manifest that caches all the commands so it's much faster to load.

Adding globby _will_ fix it, but it points to an issue with your CLIs that it needs globby at all which should be fixed.

The initial boilerplate CLIs (as far as I've ever seen) all work fine for everyone in building the manifest.

I think this leaves a few possible options:

* the manifest file is removed from the files in pjson
* the manifest build step is not being called
* something is failing but for some reason still allowing a publish

Given how frequently this seems to happen, I'm inclined to think it's the latter. It would be helpful to see a CLI or an example of exhibiting this behavior.

**Comment by rwoody** [comment]
Ok, thanks for the explanation. I now understand the purpose of those commands/files.

After generating my CLI project (within my monorepo), I removed the prepack/postpack scripts because I didn't care about updating the readme with the CLI help and I didn't see anywhere in the documentation stating it was a necessary part of building/packaging the CLI.

For starters, maybe there could be some documentation added to the [How to: Release](https://oclif.io/docs/releasing) guide describing this edge case.

Some thoughts:
* Long term, it does not seem to me (granted, this is coming from someone not familiar with the source code) that globby needs to be a dep/devDep of generated CLI projects. If the manifest is not there, the underlying package looking for the manifest should just use globby from its dependencies.
* Maybe there could be a warning (and not failure) if the installed CLI package (e.g. `@rwoody/my-cli`) meets the following conditions:
  * is installed globally from a registry (opposed to `npm link` for development)
  * does not have a manifest file

**Comment by jdxcode** [comment]
Globby is only needed in development mode. There isn't any need to have it installed for distribution, only when building a CLI so devDependency is correct here.

Ideally the CLI shouldn't even run without the manifest existing. The trouble is there isn't any way I've thought of to tell if it should be in development or production mode aside from the manifest file existing

**Comment by rwoody** [comment]
My main issue is oclif is prescribing how a project should be built unnecessarily.

The manifest could (and should) be an implementation detail. If that’s not possible to implement now, then a warning could be issued to notify the creators/users of the CLI package telling them to generate the manifest so globby doesn’t need to be required [because of performance reasons]. That would be more ideal than errors turning people away from using the package.

There are at least two solutions for preventing this error and improving the user/dev experience:
1. add globby (which occupies 4.5MB of disk space) to the dependencies and warn if it is used in a production-like environment (as I suggested earlier)
2. **cache** the manifest file the first time the CLI is run using the built-in config options

Personally, I'd prefer the caching technique so my CLI users would not be required to install dozens of dependencies that globby requires unnecessarily.

**Comment by jdxcode** [comment]
I agree that it should be an implementation detail. I would argue it is—it's only if you take out the necessary build steps that it becomes visible.

I would like to do without the build step. In the past we used to use a caching strategy but we moved to a build process and it's much preferred. It doesn't require us to write files and deal with cache invalidation (which caused us tons of issues in the past). A statically released CLI is much easier we've found.

I'm not sure how #1 would be possible. If it's added to the dependencies then it would by definition be installed into the production environment. Perhaps you could explain more your thinking there?

I think you might be misunderstanding. You don't need to install globby for users of the CLI right now. It's just needed in development to build the manifest. Putting it into devDependencies allows this behavior.

**Comment by jdxcode** [comment]
I would love to show an error (not even a warning) if the build step is removed, but I don't know any way to do that.

**Comment by samuela** [comment]
I just ran into this same error. I'm running `yarn oclif-dev manifest && yarn oclif-dev pack:macos` and
```
"files": [
    ...
    "/oclif.manifest.json"
  ],
``` 
in my `package.json` so I should have the oclif manifest in there.

**Comment by samuela** [comment]
Further update: the good stuff is included in the tar.gz, but not in the .pkg file. Installing via the tar.gz file on mac fixes the issues.

**Comment by Prakash106** [comment]
i'm also got the same error, i also add the manifiest file in package.json but still that error

**Comment by Prakash106** [comment]
`(node:26850) Warning: Mismatched version in @prakash106/got-quotes plugin manifest. Expected: 0.0.9 Received: 0.0.7
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
(node:26850) [MODULE_NOT_FOUND] Error Plugin: @prakash106/got-quotes: Cannot find module 'globby'
module: @oclif/config@1.12.12
task: not loading commands, globby not found
plugin: @prakash106/got-quotes
`

**Comment by shonfeder** [comment]
Just wanted to add that we've been fighting this unsuccessfully. We are currently trying to install the the resulting CLI app from source,  and even though we have followed the packaging instructions in https://github.com/oclif/oclif/issues/132#issuecomment-400489651 exactly, installation from source stills results in a broken intallation due to globby.

I was able to reproduce this on oclif/example-multi-ts#34. Could someone advise on one should package this to be able to install the app correctly from source?

**Comment by AllanOricil** [comment]
I ran through the steps here  and did got the globby missing dependency mesage

https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_generate_prepare.htm

![image](https://user-images.githubusercontent.com/55927613/80726588-82425b80-8afc-11ea-906b-d4c06751c30d.png)

I tried to install it globally and did not work. The message is still being displayed. Could anybody help me with it?

**Comment by vertex** [comment]
Same issue here @AllanOricil

**Comment by vertex** [comment]
I did `npm install --save-dev globby` and now it works.

**Comment by AllanOricil** [comment]
> I did `npm install --save-dev globby` and now it works.

To fix the error I had to delete .node_modules and run yarn install again.
Im using the sfdx plugins which uses Ocliff.
