### ISSUE TITLE
Feature Request/Question for user configuration

### ISSUE THREAD

**Issue by daKmoR** [oclif/oclif#136]
So I would like to have a user configuration based on where the cli is executed.

Based on the example found here https://oclif.io/docs/config.html#custom-user-configuration I assume it is not available out of the box. However is there maybe a plugin or another npm package that could be used?

Basically, it should do something like this:

Configuration Files (name could be fixed to oclif.json? or .oclif.json? or .oclifrc.json? ...):
```
home/username/oclif.json
{ foo: 'home', userName: 'John' }

project-a/oclif.json
{ foo: 'project-id-12' }

project-b/oclif.json
{ foo: 'project-id-16' }
```

Usage in showfoo.ts (psoido code): 
```js
export default class ShowFoo extends UserConfigMixin(Command) {
async run() {
  this.log(`// hey ${this.userConfig.userName}, foo is "${this.userConfig.foo}"`);
}
```

Example user interaction:
```sh
$ cd /any/path
$ mycli showfoo
// hey John, foo is "home"

$ cd project-a/
$ mycli showfoo
// hey John, foo is "project-id-12"

$ cd project-a/some/subfolder/
$ mycli showfoo
// hey John, foo is "project-id-12"

$ cd project-b/
$ mycli showfoo
// hey John, foo is "project-id-16"
```

Possible Implementation Steps:
1) check user home folder for config file
2) check current path up to / for config files
3) merge all values (in order e.g. nearest folder to current folder wins)
4) save as "this.userConfig"

So before jumpin in myself I wanted to ask if something like this makes sense... and if using a Mixin is the correct approach or if anyone has sugguestion on howto best archive that.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
