### ISSUE TITLE
Is it possible to run in DEBUG mode programatically

### ISSUE THREAD

**Issue by protoEvangelion** [oclif/oclif#143]
Instead of running the program like: `DEBUG=* ./bin/run mycli` is it possible to programmatically set `DEBUG` within the application?

My use case is the  CLI has multiple levels of logging and I would like to include `DEBUG` in the highest level of debugging.

Here are the ways I have tried to enable debugging programmatically from within a custom base class:
 
```js
process.env.DEBUG = "*"

this.config.debug = 1

this.debug.enable = true
```

By the way, absolutely fantastic job on oclif. It is by far the best node cli framework/tool I have used!

**Comment by jdxcode** [comment]
we use the debug module under the hood which does not appear to support this: https://www.npmjs.com/package/debug

we'd have to allow access to all the debug instances to enable them explicitly I think. Not impossible, but that would be a challenge for sure I think.

<img width="463" alt="screen shot 2018-07-25 at 10 45 41 am" src="https://user-images.githubusercontent.com/216188/43217998-029315a6-8ff8-11e8-81d4-eacf45157d68.png">

**Comment by protoEvangelion** [comment]
Makes sense 😄 Closing this for now and if I figure something out I will update this issue.

**Comment by jdxcode** [comment]
opening this again as we've found a good use-case for it and would like to see it ourselves

**Comment by protoEvangelion** [comment]
Wow time flies! It feels like I opened this a couple months ago haha :)

Has there been any further thought on this?

**Comment by ldhertert** [comment]
In case anyone else is trying to do this, I was able to accomplish this by editing `./bin/run` (at least for my local testing purposes) to the following.  

```
#!/usr/bin/env node

if (process.argv.indexOf('--debug') >= 0) {
    process.env.DEBUG = "*"
}

require('@oclif/command').run()
.then(require('@oclif/command/flush'))
.catch(require('@oclif/errors/handle'))
```

**Comment by coltenkrauter** [comment]
@mdonnalley – Did you close this since @ldhertert put forth a solution? 

Are there any plans to make another option to do this?

---

Regardless, I expanded on @ldhertert's solution. Assuming you want your CLI users to be able to easily enable debug mode using `cli -l debug` or `cli --log-level debug`, this solution will provide validation.

```ts
// import this into dev.js or run.js
export function setLogLevel() {
    const commandLine = process.argv.join(' ')
    const lowercaseCommandLine = commandLine.toLowerCase()
    const sanitizedCommandLine = lowercaseCommandLine.replaceAll(/\s+/g, ' ')

    if (sanitizedCommandLine.includes('-l debug') || sanitizedCommandLine.includes('--log-level debug')) {
        console.log('Running in DEBUG mode')
        console.log()
        process.env.DEBUG = '*'
    }
}
```

Also, made a `BaseCommand` to extend other commands,

```ts
import {Command, Flags, Interfaces} from '@oclif/core'

export enum LogLevel {
	debug = 'debug',
	error = 'error',
	info = 'info',
	warn = 'warn',
}

export type Args<T extends typeof Command> = Interfaces.InferredArgs<T['args']>
export type Flags<T extends typeof Command> = Interfaces.InferredFlags<typeof BaseCommand['baseFlags'] & T['flags']>

export abstract class BaseCommand<T extends typeof Command> extends Command {
  // define flags that can be inherited by any command that extends BaseCommand
  static baseFlags = {
    'log-level': Flags.custom<LogLevel>({
      char: 'l',
      default: LogLevel.info,
      description: 'Specify the log level',
      helpGroup: 'GLOBAL',
      options: Object.values(LogLevel),
    })(),
  }

  static enableJsonFlag = true

  protected args!: Args<T>
  protected flags!: Flags<T>

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  protected async catch(err: Error & {exitCode?: number}): Promise<any> {
    // add any custom logic to handle errors from the command
    // or simply return the parent class error handling
    return super.catch(err)
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  protected async finally(_: Error | undefined): Promise<any> {
    // called after run and catch regardless of whether or not the command errored
    return super.finally(_)
  }

  public async init(): Promise<void> {
    await super.init()
    const {args, flags} = await this.parse({
      args: this.ctor.args,
      baseFlags: (super.ctor as typeof BaseCommand).baseFlags,
      enableJsonFlag: this.ctor.enableJsonFlag,
      flags: this.ctor.flags,
      strict: this.ctor.strict,
    })
    this.args = args as Args<T>
    this.flags = flags as Flags<T>

    this.log('Setting ENV')
    process.env.LOG_LEVEL = flags['log-level']
    this.log('Set ENV')
  }
}
```

**Comment by mdonnalley** [comment]
Thanks @protoEvangelion - this was closed because we don't plan to support it natively in oclif since it would make a lot of assumptions about how people utilize debug logs. For instance, what if someone wants to set multiple debug env vars (e.g. `NODE_DEBUG` and `DEBUG`) whenever the `--debug` flag is provided? Or what if someone doesn't want to set `DEBUG` to `*` but rather to some other custom scope, e.g. `my-cli:*`?

Because of that, I think it's best to allow developers to implement this themselves

Both of the solutions provided in this issue are completely valid options. People can also reference how we do this for the Salesforce CLI - [here](https://github.com/salesforcecli/cli/blob/2.26.3/src/flags.ts)

**Comment by coltenkrauter** [comment]
Makes sense. Thanks 🙏
