### ISSUE TITLE
`oclif upload tarballs` assumes `...-buildmanifest` files exist, which `oclif pack tarballs` does not generate if `update.s3.host` is not set

### ISSUE THREAD

**Issue by gregsadetsky** [oclif/oclif#1447]
**Is this a bug with the oclif CLI? Or the oclif framework?**

this is a bug with the oclif CLI

**Describe the bug**

running `oclif pack tarballs` followed by `oclif upload tarballs` results in:

```
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/...path.../cli/dist/cli-v0.5.20-b453077-linux-x64-buildmanifest'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/...path.../cli/dist/cli-v0.5.20-b453077-linux-x64-buildmanifest'
}
```

---

as far as I can tell, this is happening because:
- `oclif pack tarballs` ends up calling `tarballs/build.ts`'s `buildTarget`, which has [this line](https://github.com/oclif/oclif/blob/main/src/tarballs/build.ts#L239):

```typescript
if (!c.updateConfig.s3?.host) return
```

- since in our case `update.s3.host` is not set, the function returns at that point -- the rest of this function would have otherwise generated a buildmanifest file. note that we've successfully released tarballs without the `update.s3.host` value being set before, so this is a new problem as far as we can tell
- this change/line seems to have been [introduced](https://github.com/oclif/oclif/blame/main/src/tarballs/build.ts#L239) with the release of oclif version 4
- `oclif upload tarballs` assumes that the manifest files exist [here](https://github.com/oclif/oclif/blob/main/src/commands/upload/tarballs.ts#L73) and fails in our case since the files do not actually exist

---

**To Reproduce**

- setup an oclif project, and have `oclif.update.s3.bucket` set in package.json, but not `oclif.update.s3.host`
- run:
  - `oclif pack tarballs`
  - `oclif upload tarballs`

**Expected behavior**

- either `oclif upload tarballs` should not assume that the buildmanifest files will be there (i.e. check before attempting to upload them)
- or `oclif pack tarballs` should always generate buildmanifest files regardless of whether `update.s3.host` is set..?
- in the short term, the `oclif pack tarballs` [documentation](https://oclif.io/docs/releasing/#standalone-tarballs) could state that `update.s3.host` is necessary so that manifest files are created, and for `oclif upload tarballs` to work

thanks!

**Your Environment (please complete the following information):**

- `oclif` Version: 4.13.5
- OS & version: macOS 12.7
- Shell/terminal & version: zsh 5.8.1

**Comment by mdonnalley** [comment]
Thanks for the issue @gregsadetsky 

I'm not as familiar with this part of the code base as I would like - almost of all of it predates me. But I did find some interesting clues.

That early exit was introduced in the deprecated oclif-dev cli (which is where `pack` and `upload` originally lived) by this [commit](https://github.com/oclif/dev-cli/commit/a5b73e0e843f10909aea0cfe10675544b4635b23) because of this [issue](https://github.com/oclif/oclif/issues/111)

Based on the conversation in the issue and this [code block](https://github.com/oclif/dev-cli/blob/main/src/tarballs/build.ts#L109-L112), I believe that the assumption was that you would need to set `udpate.s3.host` if you wanted to use either the `upload` command.

For some reason unknown to me, that warning was removed by this [commit](https://github.com/oclif/oclif/commit/7b4cd51b3549dc9e4fc720a9bf483c30ecd4afef#diff-d07d4d05f2b40d6a8b82c555693c646204376ab49507f8c944d6868189fad15f)

Regardless, I _think_ the correct answer here is that the host is required if you intend to use any of the `upload` commands - which, I agree, should be clearly documented.

Any reason you don't/can't set the s3 host?

**Comment by gregsadetsky** [comment]
Thanks for digging into this! I don't mind setting the s3 host of course -- and I did set it to fix this specific issue on my side (e.g. I couldn't upload the tarballs yesterday because of the missing buildmanifests - which only get built right now when the s3 host is set)

Actually, I initially set the s3 host to an incorrect value (like example.com) - which did let me pack & upload the tarballs, but then broke when I called my cli's `update` method as I got `ECONNREFUSED` 🙃 But regardless. The S3 host needs to be real, no big surprise. :-)

I agree with you - it seems that requiring the s3 host when calling `upload` would probably be the best -- i.e. it would make it obvious that a critical configuration is missing and the oclif CLI wouldn't build "incomplete" tarballs (i.e. working tarballs but no buildmanifest files)

thank you!
