### ISSUE TITLE
feat: add ability to set repository based on env or via option

### ISSUE THREAD

**Issue by Aghassi** [oclif/oclif#147]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature. Would like to have the ability to set the repository based on `GITHUB_URL` env  variable, or via an option. Why would we want this? For users in enterprise, it is a safety measure to be able to ensure that out of the box we can override repository automatically via some mechanism. This ensures that if we generate new things with OClif, we set the repo to our enterprise GitHub domain and not as external by default

What is the current behavior?
-----------------------------
Currently the user either takes the defaults or types in their own, but there is no way to override the `github.com` aspect

What is the expected behavior?
------------------------------
It should allow users to pass in a preference via the `options` variable.  This is using the latest version of OClif off of master and on 10.13.6 macOS.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
