### ISSUE TITLE
feat: dynamic target

### ISSUE THREAD

**Issue by jjangga0214** [oclif/oclif#1543]
**Is your feature request related to a problem? Please describe.**

Currently, `oclif.commands` is fixed. 

*`package.json`*:

```json
{
  "oclif": {
    "commands": "./dist/commands"
  }
}
```

Therefore, I have to compile typescript into *`dist`* to `./bin/dev.js <command>`.
I want it to be dynamic, depending on whether its runtime environment is dev or not.

**Describe the solution you'd like**

*`package.json`*:

```json
{
  "oclif": {
    "commands": {
      "dev": "./src/commands",
      "run": "./dist/commands"
    }
  }
}
```

So, `./bin/dev.js <command>` will find command from *`./src/commands`*, 
while `./bin/run.js <command>` will find command from *`./dist/commands`*.

So in the development environment, we can skip the manual build process, and make use of `ts-node` directly.

Thanks,

**Comment by mdonnalley** [comment]
@jjangga0214 `bin/dev.js` will compile your typescript at runtime automatically so there's no need to dynamically change that value

But if you absolutely have to change it, you can put your oclif configuration in a `.oclifrc.js`. Since that file is javascript, you'll be able to modify values at runtime - https://oclif.io/docs/configuring_your_cli

**Comment by jjangga0214** [comment]
@mdonnalley Interesting. In my case `bin/dev.js` does not compile ts codes automatically.
`.oclifrc.js` is good to know.
Thanks for the reply anyway :)
