### ISSUE TITLE
List nested commands

### ISSUE THREAD

**Issue by hassankhan** [oclif/oclif#155]
What is the current behavior?
-----------------------------
Currently nested commands do not show up when calling `node bin/run` from a project.

What is the expected behavior?
------------------------------
It would be awesome if `oclif` showed all the subcommands.

Please mention your oclif and OS version.
`@oclif/command`: `1.5.0`
OS: darwin-x64 node-v8.11.1 (macOS High Sierra 10.13.6)

**Comment by jdxcode** [comment]
I plan to enable this with a `--all` flag for `oclif help`

**Comment by gad0lin** [comment]
Any update on that?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
