### ISSUE TITLE
feature idea: zero-config CLI based on TypeScript index.d.ts files

### ISSUE THREAD

**Issue by wmhilton** [oclif/oclif#169]
This may be out of scope, but I think it would be cool to make a zero-configuration CLI-generator that reads a TypeScript definition file (like [isomorphic-git/index.d.ts](https://github.com/isomorphic-git/isomorphic-git/blob/master/src/index.d.ts)) and builds a "Multi-command CLI" where each `export`'ed function is a sub-command.

If anyone else is interested in this idea let me know!

**Comment by jdxcode** [comment]
I've explored the idea of zero-config in the past. I wouldn't go this route for a couple reasons though. First, it would require loading all the files which would be slow for large CLIs. The ergonomics of definitions files IMO aren't great. I'd rather do this via implementation code. This also wouldn't work for non-TS projects.

Still, if you think it's a good idea go for it. Most of the oclif code is setup in a way you should be able to reuse things like the parser easily. I'm not sure it's a great fit for this project though.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
