### ISSUE TITLE
Feature request: support for complex object flags

### ISSUE THREAD

**Issue by RomanHotsiy** [oclif/oclif#171]
Would be great to support object flags types, e.g.:

```
mycli --options.test=1 --options.theme.color=red --options.theme.font="helvetica, sans"
```

would produce the following `options`:

```js
{
  test: "1",
  theme: {
    color: "red",
    font: "helvetica, sans"
  }
}
```

I'd be happy to open a PR if it is something you don't mind merging.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
