### ISSUE TITLE
Tests fail on new `multi` project on Windows

### ISSUE THREAD

**Issue by ericis** [oclif/oclif#172]
**Steps to reproduce**
* Windows 10
* oclif multi mynewcli
* cd mynewcli
* npm run tests

**Error**
```
TSError: ⨯ Unable to compile TypeScript:
error TS6304: Composite projects may not disable declaration emit.
```

***Related to issue:** TypeStrong/ts-node#656*

**Work-around**
1. Edit `./test/tsconfig.json`
```
{
  "extends": "../tsconfig",
  "compilerOptions": {
    "noEmit": true,
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "references": [
    {
      "path": ".."
    }
  ]
}
```
2. npm run test

**Comment by jdxcode** [comment]
working fine for me. I think you might be on an old version of ts-node

**Comment by ericis** [comment]
This was a fresh install with no global installs. I will verify the version in a couple of weeks (traveling). I'll also clear the local cache.

**Comment by cleanunicorn** [comment]
I have problem running tests because it cannot see my `*.d.ts` files. Running the app works, but tests cannot see the declarations

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
