### ISSUE TITLE
--help to include section about ENVIRONMENT variables

### ISSUE THREAD

**Issue by twk-b** [oclif/oclif#181]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
FEATURE

similar to man pages, an ENVIRONMENT section should be included with top level help that includes the ENV variables and associated flag. 

What is the current behavior?
-----------------------------
cmd -h 
cmd --help

these commands do not include information about environment params. 

adding those details into the helpline itself seems error prone, and not best use of space

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

list of environment variables that can be used
list values of variables that have default, or environment var is set and found.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by UNDERCOVERj** [comment]
any update?
