### ISSUE TITLE
Can't find package.json

### ISSUE THREAD

**Issue by ZeroX-DG** [oclif/oclif#182]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
When I run tests with Oclif, it returns an error
```
Error: could not find package.json with { root: '/path/to/my/src/index.ts' }
```
I notice the error is generated because I write test with [`mock-fs`](https://github.com/tschaub/mock-fs). I can still run my test if I write the result directly to a temp directory. However, is there a way to test with `mock-fs`?

What is the expected behavior?
------------------------------
Oclif should run test normally with `mock-fs`.

**Comment by jdxcode** [comment]
This happens because mock-fs does not allow lazy requires. As we will not be removing lazy required ever, this will never function.

**Comment by teq0** [comment]
In case anyone else comes across this, as of (I believe) version 4 `mock-fs` has the ability to include parts of the actual file system to support lazy loading (see https://github.com/tschaub/mock-fs/issues/213#issuecomment-664640432), so to get it working in an `oclif` project you just need to do three things:

* include the right filesystem files and folders in your `mock-fs` config
* specify that the cwd isn't loaded by default (or you get clashes)
* make sure you do a `mock.restore()` at the end of testing so that `nyc` can write its coverage logs.

For me the code looks like 

```
import * as mockfs from 'mock-fs'
import {expect, test} from '@oclif/test'
import * as fs from 'fs'
import * as path from 'path'

const mockFolders = () => {
  const mockfsConf = {
    'package.json': mockfs.load(path.resolve(__dirname, '../../package.json')),
    'tsconfig.json': mockfs.load(path.resolve(__dirname, '../../tsconfig.json')),
    'src': mockfs.load(path.resolve(__dirname, '../../src')),
    'test': mockfs.load(path.resolve(__dirname, '../../test')),
    'node_modules': mockfs.load(path.resolve(__dirname, '../../node_modules')),
    '.nyc_output': mockfs.load(path.resolve(__dirname, '../../.nyc_output')),

    // mocked folders and files go here e.g.
    'some-file.json: `
{
  "foo": "bar"
}`,
  }

  mockfs(mockfsConf, {createCwd: false})
}

describe('hello', () => {
  test
  .do(() => {
    mockFolders()
  })
  .finally(() => {
    mockfs.restore()
  })
  .stdout()
  .command(['hello', '--name', 'jeff'])
  .it('runs hello --name jeff', ctx => {
    expect(ctx.stdout).to.contain('hello jeff')
  })
})
```
