### ISSUE TITLE
Feature idea: Error message with help prompt 

### ISSUE THREAD

**Issue by rlancer** [oclif/oclif#185]
If someone runs my API wrong I'd like to show them the help prompt.

Currently I'm doing:

```javascript
this.warn("Must provide an endpoint"); // Have to use warn as opposed to error because error will stop execution 
this._help();
```
What do you think of having a variant of the error function to log an error and show the help prompt:

```javascript
this.errorWithHelp('Must provide an endpoint')

// Or

this.error('Must provide an endpoint', {showHelp:true})
```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
