### ISSUE TITLE
building from mac for Win x86 fails

### ISSUE THREAD

**Issue by vanhumbeecka** [oclif/oclif#188]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
*bug*

What is the current behavior?
-----------------------------
- building on a Mac for Windows x64 succeeds, but for x86 fails with error about npm dependency.

steps to reproduce:
- tested with node 8.11.0 and node 10.8.0, both fail
- Because of [a bug](https://github.com/forcedotcom/sfdx-plugin-generate/issues/30) that the ```lib``` folder was not included, I first run a prepare script, that generates the ```lib``` folder with content: 
```
path-exists src && rimraf lib && tsc -b && oclif-dev manifest && oclif-dev readme && npm shrinkwrap || path-exists lib
```
- Next, I run ```yarn pack:win``` which triggers a package.json script containing: ```oclif-dev pack:win```
- This results in the screenshot below. Nothing is being build.

![image](https://user-images.githubusercontent.com/4650078/48556268-ced3b000-e8e3-11e8-8fa8-87a843fb127f.png)

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.
- @oclif/dev-cli/1.19.4 darwin-x64 node-v8.11.1 (also tested with node 10.8.0)
- macOS Mojave, Version 10.14.1

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
