### ISSUE TITLE
[Feature request] Omit sensitive flag value

### ISSUE THREAD

**Issue by afgallo** [oclif/oclif#191]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
For flags that have default values that are sensitive i.e. passwords or api keys, it would be nice to omit the actual value as opposed to the entire option (`hidden: true`) when running `$ myCli command --help`

What is the expected behavior?
------------------------------
The actual default value gets logged out to console

**Comment by jdxcode** [comment]
why use the default in this case? You could just do:

```
async run() {
  const {flags} = this.parse()
  const apiKey = flags.token || fetchDefault()
}
```

**Comment by afgallo** [comment]
The reason is my CLI tries to get some reasonable default values from config files our env variables, however, this is a best case effort since the user is not required to have these configured at all.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
