### ISSUE TITLE
[Feature request] Indicate on --help if a flag can be specified multiple times

### ISSUE THREAD

**Issue by nabeelamjad** [oclif/oclif#195]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
The `--help` command **does not** indicate if a flag can be specified multiple times.

What is the expected behavior?
------------------------------
The `--help` command indicates if a flag can be specified multiple times.

Applicable to all operating systems.
@oclif/command = 1.5.6
@oclif/config = 1.9.0

I can see the relevant code in the help plugin and could make a PR, however I'm not sure what the best way is to display that a flag is repeatable (repeatable) (required, repeatable).

**Comment by jdxcode** [comment]
I'm +1 on this (though I also don't think this is crucially important) but also agree I'm not sure what the best way to show it visually would be.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
