### ISSUE TITLE
Text color not readable on windows in ConEmu.

### ISSUE THREAD

**Issue by qurben** [oclif/oclif#208]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
A bug

What is the current behavior?
-----------------------------

 * Run `npx oclif` on Powershell or cmd in [ConEmu](https://conemu.github.io/)
 * Notice that text is not readable and the color is not reset.

 * _This behaviour is not present in the native emulator for powershell/cmd_

* Changing the color scheme does not make the text readable.

![conemu64_2019-02-19_12-19-35](https://user-images.githubusercontent.com/589651/53011534-e2416a80-3440-11e9-95f6-3d7f6782ec06.png)

What is the expected behavior?
------------------------------

Text is readable.

Windows 10, oclif version 1.12.10

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
