### ISSUE TITLE
feature request: flag implies another flag

### ISSUE THREAD

**Issue by shazron** [oclif/oclif#215]
I read the docs and I don't think this is available.

A flag implies another flag is set (that another flag is set to true). For example, if I have a flag called `--result`, it might imply another flag called `--blocking` is set.

Here's what it could look like in the `flags` config, as the `implies` key:
```
static flags = {
  result: flags.boolean({
    char: 'n',                    // shorter flag version
    description: 'output the result', // help description for flag
    implies: [ 'blocking'] // this will set `--blocking` to true
  }),
  blocking: flags.boolean({
    char: 'b',                    // shorter flag version
    description: 'block until the command is done', // help description for flag
  })
}
```

Expected:
```
# --blocking flag is set as well
my_cli my_async_command --result
```

Actual:
```
# --blocking is not set
my_cli my_async_command --result
```

**Comment by jdxcode** [comment]
I don't understand why you couldn't just do `if (flags.result || flags.blocking)`

**Comment by shazron** [comment]
just an example but It's not the same flag obviously (result has no connection with blocking at all, feature wise) which will be important for "downstream" use by passing the flags along. there can be code that is more intuitive if we just do an `if (flag.foo) then do this` versus the boolean or method, which will make the code not self-documenting.

**Comment by rhwood** [comment]
Although making the code simpler to read (because `blocking` is set correctly, so checks for `blocking` need only be for `blocking`), I think it could help the generated documentation as well if it could automatically generate (from the OP's example) the following:

```
OPTIONS
  -b, --blocking    block until the command is done
  -n, --result      output the result; this option turns on the -b option
```

"This option turns on the -O option" is the same language as in the BSD man page for `ls`. It may be more flexible to use "this implies --blocking" so a non-boolean flag could be "this implies --foo=bar"

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
