### ISSUE TITLE
refactor generator

### ISSUE THREAD

**Issue by jdxcode** [oclif/oclif#221]
The [generator](https://github.com/oclif/oclif/blob/master/src/generators/app.ts) is a lot of complex code with a lot of duplication. It would benefit from a refactor.

2 ideas to make this better:

* The app generator could be split into multiple sub-generators. yeoman supports this concept pretty well and we already use it for commands.
* flags/settings should be consolidated into a common type. [This PR](https://github.com/oclif/oclif/pull/139/files) is a good example of a simple change that required far too much duplication.

**Comment by sourabh1031** [comment]
@jdxcode i will try to work on this but please review my previous PRs . As you are already familiar with the gsoc student application period which starts on this 25th of March. :)

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
