### ISSUE TITLE
feature: allow --help to display OPTIONS in declared order

### ISSUE THREAD

**Issue by GMZwinge** [oclif/oclif#222]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Would like a feature that gives the capability for a slightly different behavior for --help.

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

Currently, the options seems to be listed in alphabetical order.
```
oclif single mynewcli --defaults --options=typescript,tslint,mocha
mynewcli/bin/run.cmd --help
describe the command here

USAGE
  $ mynewcli [FILE]

OPTIONS
  -f, --force
  -h, --help       show CLI help
  -n, --name=name  name to print
  -v, --version    show CLI version
```

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

oclif: 1.13.1
OS: Windows 10, 1703

Desired behavior: provide the capability to keep the options in the order they are declared:
```
oclif single mynewcli --defaults --options=typescript,tslint,mocha
```
Modify code to keep options in declared order.
```
mynewcli/bin/run.cmd --help
describe the command here

USAGE
  $ mynewcli [FILE]

OPTIONS
  -v, --version    show CLI version
  -h, --help       show CLI help
  -n, --name=name  name to print
  -f, --force
```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
