### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by ersinakinci** [oclif/oclif#227]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
When you create a new oclif project, the wizard asks you whether you want to use npm or yarn to install dependencies.

What is the expected behavior?
------------------------------
It would be great if [pnpm](https://github.com/pnpm/pnpm) were offered as an option for installing dependencies, as well. Should be relatively straightforward since pnpm's CLI is a superset of npm's CLI.

Using oclif v1.13.1 on MacOS 10.14.3, node-v10.15.1

**Comment by earksiinni** [comment]
Looks like this would depend on implementing a method for installing dependencies through Yeoman using pnpm. I've created a PR upstream: https://github.com/yeoman/generator/pull/1107

**Comment by earksiinni** [comment]
Apparently a previous upstream PR was already opened to support a `pnpmInstall` method in Yeoman but it's stale because the maintainers don't want to add it to core. Their reasoning is that pnpm isn't popular enough, but given the fact that I independently opened up my own PR without any knowledge of the previous one, I'd say that's a good sign that it's popular enough! https://github.com/yeoman/generator/pull/1067

Anyway, I went ahead and opened my own PR here that adds pnpm support and does it in a way that the upstream maintainers recommend: https://github.com/oclif/oclif/pull/228

**Comment by RasPhilCo** [comment]
Interesting. We haven't used pnpm so I'm yet unaware of larger effects for the project but I'll try to look into it further.

**Comment by GiancarlosIO** [comment]
Are there any updates to this? 😢

**Comment by pieroproietti** [comment]
It's few days I discovered pnpm, I was on the point of give up my project - a remaster system for linux - based on oclif becouse the long time to install and compile. After installing pnpm the problem is partially solve, install packages it's a breeze and take less than a minute compared to npm (about 5 minutes). Of course the problem remain building deb packages: oclif use npm or yarn (my tests was with npm) and seem wo install packages witn pnpm is compatible with build the packages final with  oclif traditional npm. But - of course - it again take long time to download and install packages in order to build .deb.

Looking the effort of [DesertDevErsin](https://github.com/DesertDevErsin) I saw he used an old version of oclif, and probably end with same problems... 

There is something of new, indication where I can try to add pnpm in the processo of building packages with oclif.

Thanks

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by pieroproietti** [comment]
For my project I have slightly modified oclif by creating an [oclif-pnpm](https://github.com/pieroproietti/oclif-pnpm) package and including support for pnpm instead of npm. Obviously it cannot be included as is, but if there is interest I would like to collaborate on pnpm support for oclif.

**Comment by kibotrel** [comment]
Any update on this? It would be awesome to support it takes less disk space, dependencies installation is real fast and much more!

**Comment by woss** [comment]
it's 2024, npm is long forgotten

**Comment by pieroproietti** [comment]
@woss, The latest versions of oclif, I don't remember how long, but they can be used with pnpm.

**Comment by ersinakinci** [comment]
@woss did you mean that pnpm is long forgotten? I see people using it everyday. [It's even more popular than yarn](https://npmtrends.com/pnpm-vs-yarn).

Sadly, I moved on from oclif due to lack of pnpm support. My PR never got merged. Glad to hear that it's supported now. (Ironically, I don't use pnpm anymore.)

**Comment by woss** [comment]
@ersinakinci I meant npm. Pnpm is amazing :)

**Comment by gaurav21r** [comment]
> [@woss](https://github.com/woss) did you mean that pnpm is long forgotten? I see people using it everyday. [It's even more popular than yarn](https://npmtrends.com/pnpm-vs-yarn).
> 
> Sadly, I moved on from oclif due to lack of pnpm support. My PR never got merged. Glad to hear that it's supported now. (Ironically, I don't use pnpm anymore.)

Is `pnpm` supported now? I don't see it in the official ocs @pieroproietti @mdonnalley

**Comment by pieroproietti** [comment]
yes, pnpm it is supported.
