### ISSUE TITLE
Character to separate package name and version

### ISSUE THREAD

**Issue by lorenzleutgeb** [oclif/oclif#230]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
I want to request a feature.

What is the current behavior?
-----------------------------
 1. Create a new CLI with oclif.
 1. Assumption: The package is named `x` and its version is `1.0.0`.
 1. Execute it's `help` subcommand.
 1. Observe that the version output is:
```
x/1.0.0
```

What is the expected behavior?
------------------------------
For a package named `x` with version `1.0.0` the version output should state:

```
x@1.0.0
```

This format appears with `npm`:

```
$ npm install --help
...
npm install [<@scope>/]<pkg>@<version>
...
```

As well as with Yarn (see [`yarn add`](https://yarnpkg.com/lang/en/docs/cli/add/#toc-adding-dependencies)).

I think that this would require changes in oclif/config as well as oclif/plugin-help. Also, it is understandable that others prefer other separators (like `/` or ` `), but it would be interesting to have this configurable in some way.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
