### ISSUE TITLE
Capture unhandled  errors to report to Sentry

### ISSUE THREAD

**Issue by mhemrg** [oclif/oclif#231]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
It's a question.

What is the current behavior?
-----------------------------
It seems that Oclif captures all unhandled errors.

What is the expected behavior?
------------------------------
We should have a way to capture unhandled errors to send to Sentry. How can we do this?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
