### ISSUE TITLE
Topic Aliases

### ISSUE THREAD

**Issue by jaguilar87** [oclif/oclif#237]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature 

What is the expected behavior?
------------------------------
Is there a way to refer a topic with different names? Right now I got away using a symlink, but that would not work on all OS. 

I'm guessing that we could go with something like:

```
   "topics": {
       "package": { "aliases: ["pkg"], ....
```

https://github.com/oclif/config/blob/647a78eec720cc7bbf4aa154fb54131eb601be19/src/config.ts#L342

```
findTopic(name: string, opts: {must?: boolean} = {}) {
    let topic = this.topics.find(t => t.name === name || t.alias.includes(name))
```

But I am still lacking a lot of context about the project.

Let me know what you think!

**Comment by from-nibly** [comment]
Agreed would like this, right now I'm resorting to a matrix of command level aliases. I'm guessing this feature would be non trivial if you didn't want to make a breaking change to the aliases field in the command, as that field expects the full "topic path" as the alias.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
