### ISSUE TITLE
Unexpected flags after multiple flags fail silently

### ISSUE THREAD

**Issue by markmartirosian** [oclif/oclif#249]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

High severity bug ⚡ (cc: @jdxcode)

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

```sh
$ cmd --multiple-flags abc --multiple-flags bcd --invalid-flag
# No error
```

What is the expected behavior?
------------------------------

```sh
$ cmd --multiple-flags abc --multiple-flags bcd --invalid-flag
ERROR: Unexpected arguments: --invalid-flag
```

```json
{
    "@oclif/command": "1.5.14",
    "@oclif/config": "1.13.0",
    "@oclif/errors": "1.2.2",
    "@oclif/plugin-help": "2.2.0",
}
```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
