### ISSUE TITLE
No documentation for command with arguments in JavaScript

### ISSUE THREAD

**Issue by janpio** [oclif/oclif#253]
Seems the current documentation on https://oclif.io/docs/args is only available for TypeScript, not JavaScript. (For flags this is also the case, but the generated command includes a flag by default.)

After a bit of playing around I came up with this:

```
const {Command} = require('@oclif/command')

class MoveCommand extends Command {
  async run() {
    const {args} = this.parse(MoveCommand)
    this.log(`hello ${args.releaseName} from ...\\src\\commands\\apache\\move.js`)
  }
}

MoveCommand.description = '...'

MoveCommand.args = [
  {
    name: 'releaseName',
    required: true,
    description: 'name of release to move',
  },
]

module.exports = MoveCommand
```

All correct?
If so, could this somehow be added to the docs? (Of course abstracted to the level of the TypeScript example)

**Comment by mbejda** [comment]
Works for me 👍

**Comment by buonzz** [comment]
thanks for this @janpio - you are the hero we need

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
