### ISSUE TITLE
Custom type declaration not recognized

### ISSUE THREAD

**Issue by jspruance** [oclif/oclif#255]
What is the proper way to add a custom type declaration to a TyeScript Oclif project?

I am using the 'mock-stdin' npm module, which doesn't have a type declaration file, so I am writing my own. I've placed it in the 'src' folder in the project root, per tsconfig 'rootDir' settings but when I run the unit tests I get a "Could not find a declaration file for module 'mock-stdin'."

**Comment by lukasreichart** [comment]
@jspruance did you find a solution for this problem?

**Comment by jspruance** [comment]
@lukasreichart i never did figure it out. due to time constraints i just ended up switching to 'nock' instead.

**Comment by RasPhilCo** [comment]
I'll have to repro and mess with this! (Not sure when but I'll put it in my backlog.)

**Comment by peteremiljensen** [comment]
Adding the following to `.tsconfig` fixes it on my side:

```json
"ts-node": {
  "files": true
}
```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
