### ISSUE TITLE
update plugin-help documentation

### ISSUE THREAD

**Issue by RasPhilCo** [oclif/oclif#256]
`@oclif/plugin-help` is baked in `@oclif/command`. It is also included in `oclif.plugins` via the generators so that the command `help` itself shows up in the root help `COMMANDS` output. But this has been confusing.

1. For now, include `@oclif/plugin-help` as a peerDependency in `@oclif/command`
2. Decouple help via https://github.com/oclif/command/issues/61

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
