### ISSUE TITLE
A subcommand named "index" seems to be ignored

### ISSUE THREAD

**Issue by spaghetti-is-pasta** [oclif/oclif#260]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Adding an `index.js` file to the `commands` in order to allow `$ cmd index ...` doesn't seem to work. The subcommand is ignored.

**Comment by RasPhilCo** [comment]
`index` is a special file name for topics, you can work around that with this `src/commands/index/index.js`.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
