### ISSUE TITLE
Combining flag with {multiple: true} with a single argument doesn't work

### ISSUE THREAD

**Issue by spaghetti-is-pasta** [oclif/oclif#261]
I have a command that should work like:

```
  $ foo bar --filter a --filter b myfile.txt

```
`--filter` is defined with `{ multiple: true, options: [ 'a', 'b', 'c'] }`, and I've defined a single argument. However, invoking the above reports:

```
Error: Expected --filter=myfile.txt to be one of a, b, c
```
The workaround is to terminate the flags sequence using `--` thusly:

```
  $ foo bar --filter a --filter b -- myfile.txt
```
But most users won't know or understand how to get from the reported error to that solution. I understand that it's attempting to allow for:  `$ foo bar --filter a b <file>` and it cannot distinguish the file argument from an additional filter argument. This is why allowing for `--filter a b` to be the same as `--filter a --filter b` is quite hazardous in my opinion. 

Nonetheless I think a smarter algorithm should be able to make sense of the above usage (without the `--`). It knows there is an expected argument on the RHS.

**Comment by firefish5000** [comment]
Here is a slightly different example that may paint this in a slightly darker light
```js
    strict: oFlags.boolean({
      ,'default': false
    })
    ,extensions: oFlags.string({
      'default': ['.js']
      ,'multiple': true
      ,'description': 'List of valid file extensions'
    })
    ...
  // 
  static strict = false
  ...
     const { flags: {extensions} ,argv: walkPaths } = this.parse(MyCommand)
     console.log(extensions)
```

```sh
myProg --extensions .js .ts --strict ./myDir1 ./myDir2
# prints [ '.js', '.ts', './myDir1', './myDir2' ]
```
As you can see, `--extensions` keeps reading the args even though `--strict` breaks it up. This is highly unexpected.
`--flag eats multiple` is somewhat rare, but is a thing that is occasionally done. Using `--` to signify the end of flags is a common convention which users could guess and it acts as an ok workaround. 
But, parsing flags out from in-between the list, instead of just ending the list when another flag is seen is highly unexpected.
And the fact this occurs makes me wonder what happens when multiple flags with multiple enabled are specified  (I have not tested nor looked at the code yet)

Another potential issue, `--flag=something`
```js
myProg --extensions='.js' --strict ./myDir1 ./myDir2
# prints [ '.js', './myDir1', './myDir2' ]
```
I am unsure of standards, but intuitively I think the equal sign in `--flag='someValue'` should signify that the flag is only getting 1 argument (or that it is a comma-separated argument list). Even ignoring the likely erroneous behavior where it keeps reading after `--strict`

The rules I recommend are as follows

1) If another flag is found directly after a flag that is looking for input, the flag should treated as input to the previous flag instead of as a flag itself. A flag expecting input should always treat the data directly after it as input.
2) If another flag is found while looking for input for a previous flag, the previous flag should end its search for input there.
3) For single character flags, only 1 character may be a flag that requires input. 
4) If `=` seperates the flag from its args instead of a space, treat the rest of the arg (everything to the next space) as the flags input and do not attempt to gather more input after the space.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
