### ISSUE TITLE
"required" and "default" annotations should appear to the *right* of the flag description

### ISSUE THREAD

**Issue by spaghetti-is-pasta** [oclif/oclif#262]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
feature

What is the current behavior?
-----------------------------
the notations `(required)` and `[default: xxx]` appear to the *left* of the description in the usage.

What is the expected behavior?
------------------------------
I think these are less important than the primary command description and should appear to the right of the description.

**Comment by RasPhilCo** [comment]
I'll keep this in mind when we build help templating.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
