### ISSUE TITLE
Mixing flags that use "char" and ones that do not, produce unaligned help

### ISSUE THREAD

**Issue by spaghetti-is-pasta** [oclif/oclif#263]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
feature

What is the current behavior?
-----------------------------
Mixing flags that use "char" with ones that do not, produces unaligned help:

```
  -e, --end=end                                            Do something
  -s, --start=start                                        Do something
  --out=out                                                Write to out
```

What is the expected behavior?
------------------------------

```
  -e, --end=end                                           Do something
  -s, --start=start                                       Do something
      --out=out                                           Write to out
```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
