### ISSUE TITLE
actual command gets executed before init hook execution is complete

### ISSUE THREAD

**Issue by francisminu** [oclif/oclif#266]
Hi,
We have an inithook added in our project for authentication.
We are using the 'request' library to make a call to fetch the token. 
When we run a command, eg: mycli command1, the expectation was that command1 will be executed only after the complete execution of inithook, however, command1 is executed even before the request call in the hooks get over.

Thanks,

**Comment by RasPhilCo** [comment]
Are you returning a promise?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
