### ISSUE TITLE
feature request: hide added plugin commands

### ISSUE THREAD

**Issue by RasPhilCo** [oclif/oclif#269]
Currently added plugins' commands are all public. Maybe with a `hidden` property in package.json, added plugins could be hidden commands.

ref: #267

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by gonzaloriestra** [comment]
I also think this would be nice.

As a workaround, you can hide the `plugins` topic from the package.json:
```
"oclif": {
  "topics": {
    "plugins": {
      "hidden": true
    }
  }
}
```

And create a wrapper to override the `plugins` command:

```
// commands/plugins/index.ts
import PluginsIndex from '@oclif/plugin-plugins/lib/commands/plugins/index.js'
import {Command} from '@oclif/core'

export default class Index extends Command {
  static hidden = true

  async run(): Promise<void> {
    await PluginsIndex.default.run(this.argv)
  }
}

```
