### ISSUE TITLE
Use `parse` to fix mistyped arguments but still use `options`?

### ISSUE THREAD

**Issue by janpio** [oclif/oclif#270]
I am currently building a CLI using `oclif` - thanks for creating it ❤️ 

My users will probably mistype some of the allowed arguments. I see I can use `parse` to fix those by maintaining a list of common corrections, but as I still want to provide the `options` (for the help output) the `parse` is never actually executed and an error is thrown if they don't use one of the defined list of options.

Is there a way to work around that?

**Comment by RasPhilCo** [comment]
Parse happens after options validation https://github.com/oclif/parser/blob/05f89e04e21b95a4e262c9aebbe3809ada2db742/src/parse.ts#L177

But I'm open to discussion! The one concern I have, off the top of my head, is fixing input for users without telling them is a bad practice, but I'm not sure if oclif should care if you, as an oclif developer, are doing that.

**Comment by janpio** [comment]
Aha, so line 174 uses `include` to check if the value is included in the array, then line 177 calls `parse` - got it.

> The one concern I have, off the top of my head, is fixing input for users without telling them is a bad practice, but I'm not sure if oclif should care if you, as an oclif developer, are doing that.

You raise a good point, let me explain my usecase: 
I build a meta CLI that will be used by users of different other tools, that have slightly different naming for the same concept (e.g. development, debug, dev vs. production, release, appstore, app-store). I want to choose one of those as the canonical correct one for the documentation (and also to have a consistent model of what is going on), but I am 100% sure people will still try the one they know from their tool first.
So I thought it would be nice to just deal with it be replacing their suboptimal argument with the correct one and call it out with a `log` to educate. I can do that in `parse`, but only if I add all of them to `options` which will also output them in the help - which of course makes them "real" options as well - and that's not what I want.

I thought that maybe `options` could be a method and depending on a context param I could return different things to the help menu than to the actual command (which would also have allowed other use cases), but that is obviously not the case.

The only workaround I can think of right now is to no define any `options` and fully validate the options manually in `parse`, which loses the help output of for me. Other option of course is to abandon the idea of fixing arguments.

**Comment by janpio** [comment]
I have another usecase that probably hits the same lines of code, wrote it down here just as additional input: https://github.com/oclif/oclif/issues/272

**Comment by dotnetCarpenter** [comment]
> but I am 100% sure people will still try the one they know from their tool first.

@janpio a CLI program should be _scriptable_ and expandable. That is, a flag or command should never change. Do yourself a favor and never try to fix user input. It is much better to fail hard. Your program might have a human user, but is very likely to be used in CI/CD context. Be used by other CLI's etc. Having many ways to same the same is a code smell and will hinder maintenance in the long run.

This my opinion and your are not obligated to follow my advice in any way. But I would hate if this became _best practice_ in oclif.

**Comment by LassiterJ** [comment]
I too was looking to have the input parsed before checking if the options were ran. For my use case, I was intending to change the case of the user input to match the named classes I have as the options. How it is currently set I would have to add the different cases to the options array rather than just letting the parse function standardize the case for me. Now I am implementing my own version of option validation as a workaround. I understand its not a best practice to fix user input but I don't think its bad to correct case or alias a command in the background.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
