### ISSUE TITLE
behavior of exclusive property of flags

### ISSUE THREAD

**Issue by RasPhilCo** [oclif/oclif#275]
1) help should display flag exclusivity. currently it shows nothing.
2) exclusive flags should be allowed to be required exclusively. currently all "required" exclusive flags have to be not required and later checked for presence in `run`.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
