### ISSUE TITLE
deprecate node 8 after Jan 1, 2020

### ISSUE THREAD

**Issue by RasPhilCo** [oclif/oclif#279]
Waiting on:
- [ ] node-12 support https://github.com/oclif/oclif/issues/278

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
