### ISSUE TITLE
"multiple" flag for args

### ISSUE THREAD

**Issue by mkg20001** [oclif/oclif#293]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
feature

What is the current behavior?
-----------------------------
When the `multiple` flag is used on an arg, nothing happens

What is the expected behavior?
------------------------------
It should instead allow one specific argument to be supplied multiple times.

This should technically also work if there are arguments after that argument, as long as only one argument is flagged with multiple.

Please mention your oclif and OS version.

    "@oclif/command": "^1",
    "@oclif/config": "^1",
    "@oclif/plugin-help": "^2",
Ubuntu 19.04 amd64

**Comment by RasPhilCo** [comment]
Set `static strict = false`, see bottom of https://oclif.io/docs/args.

**Comment by G-Rath** [comment]
@RasPhilCo do you have an example on how to read the values?

If I set `strict` to `false`, oclift doesn't error, but only captures the first argument when I'd like it to capture all arguments (aka a variadic argument).

**Comment by mkg20001** [comment]
See PR for this issue here, btw: https://github.com/oclif/parser/pull/63

**Comment by G-Rath** [comment]
@mkg20001 awesome cheers for that.

I'm happy to help get that across the line, if there's anything I can do to help unblock it.

/cc @RasPhilCo

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by dariober** [comment]
I'm looking for this feature myself - I wonder if there is any update...? I'm using:

```
"@oclif/core": "^3.18.2",
"@oclif/plugin-help": "^6.0.8",
"@oclif/test": "^3.1.3",
 "oclif": "^4.4.2",
```
