### ISSUE TITLE
Possible to run pre-compiled commands instead of relying on ts-node?

### ISSUE THREAD

**Issue by jayalfredprufrock** [oclif/oclif#294]
Is there any way to run a pre-compiled oclif project _without ts-node_? 

Our CLI tool lives in a monorepo that uses a shared ts-config file and includes strict eslint rules. Looking at the oclif source, ts-node appears to be setup to bypass loading the tsconfig.json file and instead manually recreates one, preserving a subset of settings from the detected tsconfig.json. Unfortunately it's not smart enough to respect the "extends" option in tsconfig, so I first had to duplicate options like "esModuleInterop" before they would get picked up. I also discovered that the way it resolves typeRoots doesn't really work OOTB in a lerna-based monorepo that hoists dependencies outside the child package's node_modules folder. 

I guess what I'm getting at is that I feel like I'm fighting ts-node here, when I'm already compiling all my commands down with tsc anyway. Also, even simple commands seem to suffer from a bit of a startup delay while ts-node does it's stuff.

**Comment by yordis** [comment]
I recently had to remove `ts-node` due to the issue that I had to pass a config that point to a JavaScript file from inside my project and I used `__dirname`

```js
// Most be `.js`
const pluginFile = path.resolve(__dirname, '../plugins.js');
```

Since this will produce `src/whatever/plugins.js` instead of `dist/whatever/plugins.js` I had to remove `ts-node` and use `tsc` directly.

**Comment by 0xdevalias** [comment]
This could be something that has changed since the original issue was created, but I believe that `ts-node` is only used in the `bin/dev` stub these days, so using `bin/run` wouldn't use `ts-node` at all:

- https://github.com/oclif/hello-world/tree/main/bin
  - https://github.com/oclif/hello-world/blob/main/bin/dev
  - https://github.com/oclif/hello-world/blob/main/bin/run

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
