### ISSUE TITLE
Support an automatic version switching mechanism like nvm

### ISSUE THREAD

**Issue by Aghassi** [oclif/oclif#297]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

N/A

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

I'd like to have the ability for a CLI to respect a version set in an `rc` file, similar to how `nvm` works. The reason for this is because when we have a CLI, we introduce the potential for version drift at scale. When I have 8 people on a team, how do I ensure the CLI that team uses is the same version on every person's computer? This use to be solved by a lock file for us when the version was set in the package.json, but since the CLI doesn't live there anymore we lost this. 

Having an `rc` file that allows us to say "CLIs running in this repo should use version X" would be beneficial to our needs.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
