### ISSUE TITLE
Support custom tsconfig file

### ISSUE THREAD

**Issue by G-Rath** [oclif/oclif#299]
`oclif` has a hard requirement on `tsconfig.json`.

I should be able to specify the name of my `tsconfig.json`, & it's path (ideally), i.e

```
  "oclif": {
    "commands": "./lib/commands",
    "tsconfig": "tsconfig.build.json",
    "bin": "mycommand",
    "plugins": [
      "@oclif/plugin-help",
      "@oclif/plugin-autocomplete"
    ]
  }
```

**Comment by khayalan-mathew** [comment]
For future references I leave this here, it seems like this line needs to be adapted to support a custom tsconfig:
https://github.com/oclif/config/blob/master/src/ts-node.ts#L26

**Comment by fwoelffel** [comment]
It looks like having a configuration `tsconfig.json` path would probably not be enough as not all values are actually used. See https://github.com/oclif/config/blob/master/src/ts-node.ts#L68

What's your usecase? Mine is to use `oclif` to build a CLI in a Nx monorepo and reuse some of our libs. Not being able to use our custom `tsconfig.json` might leave us with no other choice than using some other lib.

**Comment by mshwery** [comment]
I'm in a similar boat. I would love to use oclif in a monorepo, but without support for either custom tsconfig paths or without respecting `extends` (#488) it's a non-starter.

**Comment by amphro** [comment]
I would like to get this into oclif/core instead. Thoughts?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
