### ISSUE TITLE
Support custom typescript package

### ISSUE THREAD

**Issue by G-Rath** [oclif/oclif#300]
Currently, oclif has a hard dependency on `typescript`, meaning we can't use transformers when running locally.

For example, I use `ts-transformer-paths` w/ `ttypescript` to support transforming `paths` at compile time to their relative equivalent.

Personally, I think it would be acceptable to use `ttypescript` over `typescript`, as it's a thin-wrapper that simply lets you use transformers w/ TypeScript.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
