### ISSUE TITLE
Tests run against lib, not src

### ISSUE THREAD

**Issue by geelen** [oclif/oclif#310]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Bug... sorta.

What is the current behavior?
-----------------------------
Generate a new multi-command project, build it, test it (it works), then change the implementation to falsify the tests without re-building. The tests still pass, since `lib/commands/hello.ts` hasn't been updated.

What is the expected behavior?
------------------------------
The tests should fail, since `src/commands/hello.ts` is broken.

---

You can "fix" this by changing the `oclif` section of `package.json` to include:

```js
  "commands": "./src/commands",
```

(as opposed to `./lib/commands`) but obviously, when publishing, you want the `lib` directory used.

Is there a way to tell oclif to test against `src` but publish against `lib`?

**Comment by RasPhilCo** [comment]
I wasn't able to reproduce this. Changing the implementation failed the tests. Do you have to produce exact steps?

**Comment by prokopsimek** [comment]
I have a similar issue with the multi-command CLI. The problem is, that `package.json` loads built JavaScript for runtime but it's not possible to test it directly with `./bin/run` because the source code is not compiled. The package.json contains configuration for oclif commands (`"commands": "./lib/commands"`) that navigates directly to the `lib` folder instead of `src`.

Questions: Is it possible to load commands dynamically in `./bin/run` and remove commands config from package.json?

Can you propose any other solution?

**Comment by y-lakhdar** [comment]
I also had the similar issue once I started using oclif/core.
The workaround I found at the moment (without changing the `package.json` command parameter) is to call the command programmatically from the tests.

So instead of using `test.command(['hello'])`
I import the hello command from the src file 
```
import Hello from 'path/to/src/commands/hello';
// ...
await Hello.run([]);
```

However, I would prefer another solution where I don't have to manually import my commands.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
