### ISSUE TITLE
Invalid dirs on scoped package

### ISSUE THREAD

**Issue by svrooij** [oclif/oclif#315]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Report a bug

What is the current behavior?
-----------------------------
1. Create a package with a [scoped](https://docs.npmjs.com/about-scopes) name (like `@svrooij/sonos`)
2. Try add something to the dataDir(/configDir/cacheDir).
3. `Error: ENOENT: no such file or directory, mkdir '/Users/myuser/.local/share/@svrooij/sonos-cli'`

The `@` character isn't allowed as first character in a directory name.

What is the expected behavior?
------------------------------
I would expect oclif to cleanup the path name so that it at least is a legal path. Think just stripping the @ sign would be enough.

```JSON
{
"@oclif/command": "^1.5.19",
"@oclif/config": "^1.13.3"
}
```

Please mention your oclif and OS version. OS is mac, but suspect others are also affected.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
