### ISSUE TITLE
Hosting tarballs on Azure

### ISSUE THREAD

**Issue by stalmok** [oclif/oclif#316]
Would you be able to provide some documentation on how to host tarballs in Azure's file storage? Currently the docs has the following, which doesn't give much guidance on how to do it if not using S3.

> If you don't want to use S3, you can still run oclif-dev pack and it will build tarballs. To get the updater to work, set oclif.update.s3.host to a host that has the files built in ./dist from oclif-dev pack. This host does not need to be an S3 host. To customize the URL paths, see the S3 templates in @oclif/config.

**Comment by judedaryl** [comment]
@RasPhilCo with the update to oclif 2.0.0, we are being forced to use s3. would it still be possible to customize this behavior by separating the "build" and "upload" parts of the promote command?

**Comment by mattbishop** [comment]
+1 for this problem. Every S3 vendor out there charges for the service, while we really just need http naming conventions more clearly stated and supported.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
