### ISSUE TITLE
Oclif Topics not working with Windows

### ISSUE THREAD

**Issue by jooshkins** [oclif/oclif#328]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug 

What is the current behavior?
-----------------------------
Oclif topics appear to not work with windows. ( tested with both cmd and powershell )

To reproduce:
1. create new oclif
`npx oclif multi`
2. create multi command 
`npx oclif command stinky:poo`
3. run command
`./bin/run stinky:poo`
4. receive error
```
.\bin\run stinky:poo
 »   Error: command stinky:poo not found
```
The generator command `npx oclif command stinky:poo` does not produce any errors and the correct file and folder structure seem to be in place after running the command.
Also after running `npx oclif-dev manifest` the commands are not in the `oclif.manifest.json`

What is the expected behavior?
------------------------------
Tested on Windows 10 1903
The same sequence of steps worked on macOS High Sierra 10.13.6

Thanks, 8-)

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
