### ISSUE TITLE
debug typescript projects in vs code

### ISSUE THREAD

**Issue by cyrfer** [oclif/oclif#329]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug. Where are my variables?

![image](https://user-images.githubusercontent.com/4392990/75065749-48baf780-549e-11ea-825b-8dd38844fe68.png)

How can I use the VS Code debugger with project generated for typescript?

What is the current behavior?
-----------------------------
Steps to reproduce the problem:
1. generate a new cli multi project for typescript
2. setup vs code to debug ([this tip](https://github.com/oclif/oclif/issues/135#issuecomment-585393880) got me something) mocha tests
3. run mocha test using vs code debugger
4. wonder where your variables are

What is the expected behavior?
------------------------------
```bash
$ oclif -v
oclif/1.15.2 darwin-x64 node-v12.3.1
```

Expected:

1. starting the debugger should not move the user's breakpoints
2. when the debugger stops at a breakpoint, vs code should display the local variables for the local context of the breakpoint.
3. a properly configured `.vscode/launch.json` is generated when a new project is generated
4. a command can add a properly configured `.vscode/launch.json` to existing projects

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
