### ISSUE TITLE
[feature request] specify subcommand delimiter, or at least allow space as an option

### ISSUE THREAD

**Issue by trusktr** [oclif/oclif#331]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

feature

What is the current behavior?
-----------------------------

`my-cli foo:bar:baz`

What is the expected behavior?
------------------------------

Ability to instead do

```
my-cli foo bar baz
```

with spaces instead of colons. The spaces are more commonplace. Also it is easier to type spaces. It'd be nice to have them.

Maybe allowing to specify the delimiter would be better than just allowing a space option? f.e.

```
my-cli foo.bar.baz
```

but personally I just want spaces.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
