### ISSUE TITLE
DepricationWarning: Configuration via mocha.opts is DEPRECATED

### ISSUE THREAD

**Issue by pateash** [oclif/oclif#340]
>OS : MacOs Mohave
>Oclif :oclif/1.15.2 darwin-x64 node-v12.9.0

What is the current behavior?
-----------------------------
I am getting following DeprecationWarning on in **ocliftest** on brand new oclif cli.
```js
npm test
```
>node:9787) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.

What is the expected behavior?
------------------------------
new Oclif template should contain **RC** file or configs in **package.json** instead.

**Comment by darkmavis1980** [comment]
This would be easily solvable, we just need to remove the `mocha.opts` file, and replace with a `.mocharc.json` file with this content:

```
{
  "extension": ["ts"],
  "spec": "test/**/*.test.ts",
  "require": "ts-node/register",
  "recursive": true,
  "reporter": "spec",
  "timeout": 5000
}
```

And then upgrade mocha to the latest version.
I was about to do it myself, but then I noticed that in the current `mocha.opts` you use some ejs templating:

```
<%= ts ? '--require ts-node/register\n--watch-extensions ts\n' : '' _%>
--recursive
--reporter spec
--timeout 5000
```

And I'm not sure if you can do the same inside a JSON file

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by darkmavis1980** [comment]
It seems that it has been fixed a while ago
