### ISSUE TITLE
Is this project still active or maintained

### ISSUE THREAD

**Issue by austinbv** [oclif/oclif#344]
We are curious before we invest in the project is it still active or maintained? The last pull request accepted was ~5 months ago and the last commit around the same time.

If abandoned, are there plans on handing maintainership to the community?

**Comment by RasPhilCo** [comment]
This repo is just the CLI generator. Development happens across the other 10-15 oclif repos.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
