### ISSUE TITLE
moderate vulnerability associated to mocha 5.2.0

### ISSUE THREAD

**Issue by gkpty** [oclif/oclif#348]
BUG

oclif version 1.16.1

when mocha is added to the build it adds mocha 5.2.0. this version has a vulnerability associated to minimist <= 0.2.1

fixed by updating mocha to version 7.1.2

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
