### ISSUE TITLE
Bug: TypeError: this.pjson.repository.startsWith is not a function

### ISSUE THREAD

**Issue by moltar** [oclif/oclif#354]
What is the current behavior?
-----------------------------

Running `oclif multi` inside existing project with an existing `package.json` with the following:

```
  "repository": {
    "type": "git",
    "url": "git@github.com:foo/bar.git"
  },
```

Get the following:

```
❯ oclif multi

     _-----_     ╭──────────────────────────╮
    |       |    │      Time to build a     │
    |--(o)--|    │  multi-command CLI with  │
   `---------´   │  oclif! Version: 1.16.1  │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? command bin name the CLI will export tools
? Select a package manager npm
? TypeScript Yes
? Use eslint (linter for JavaScript and Typescript) No
? Use mocha (testing framework) No
? Add CI service config
missing bugs
package.json fixed!
TypeError: this.pjson.repository.startsWith is not a function
    at App.writing (~/foo/node_modules/oclif/lib/generators/app.js:320:68)
    at Object.<anonymous> (~/foo/node_modules/yeoman-generator/lib/index.js:424:27)
    at ~/foo/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at ~/foo/node_modules/run-async/index.js:26:19
    at ~/foo/node_modules/yeoman-generator/lib/index.js:425:13
```

What is the expected behavior?
------------------------------

Not throw errors.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
