### ISSUE TITLE
ts-node issues

### ISSUE THREAD

**Issue by RasPhilCo** [oclif/oclif#388]
Collating ts-node issues:
https://github.com/oclif/oclif/issues/333
https://github.com/oclif/config/pull/44
https://github.com/oclif/config/issues/98

**Comment by RasPhilCo** [comment]
custom tsconfig path: https://github.com/oclif/oclif/issues/299

**Comment by RasPhilCo** [comment]
https://github.com/oclif/oclif/issues/403

**Comment by RasPhilCo** [comment]
Also https://github.com/oclif/oclif/issues/445

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
