### ISSUE TITLE
Disable ts-node

### ISSUE THREAD

**Issue by MarcoScabbiolo** [oclif/oclif#403]
*Feature*
-----------------------------------------------------

Have a different entry point file in `bin` other than `run` like `run-node` with `ts-node` disabled

What is the current behavior?
-----------------------------

Using a standard typescript setup with oclif is painful when attempting to debug with VS Code.
Even if I have a `lib` directory with source maps properly set up oclif will use `ts-node` to somehow find my `src` directory and transpile the files, resulting in an invalid output different from my `lib` for some reason.

I'm sure they are proper ways to handle this issue with `ts-node` but it is much easier if oclifs stops using `ts-node` in the first place.

Right now I have to rename `tsconfig.json` into `hiddentsconfig` before debugging and restore it after debugging so `ts-node` fails at attempting to find and transpile my typescript and uses the actual code i told oclif to use.

What is the expected behavior?
------------------------------

If I say my commands are at `lib/commands` I expect oclif to use those files instead of transpiling my `src` on its own.

**Comment by natew** [comment]
Just ran into this, it's quite hard to figure out at first and very confusing... a simple flag to disable the automatic ts-node resolution would be a big help.

**Comment by mshwery** [comment]
Looks like you can do `OCLIF_TS_NODE=0` based on this
https://github.com/oclif/config/blob/9683516aab18865836c854a90e6d49fe24999b65/src/ts-node.ts#L51

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
