### ISSUE TITLE
npm publish not updating README.md

### ISSUE THREAD

**Issue by james-hu** [oclif/oclif#429]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------
After running `npm publish`, README.md remain unchanged

What is the expected behavior?
------------------------------
README.md should be updated with information regarding command line flags and arguments. The documentation of oclif does not say this explicitly but I guess this is what should happen. Maybe the documentation can be updated to clarify a bit.

This is my code repo: https://github.com/james-hu/apig-swagger-ui

**Comment by RasPhilCo** [comment]
Is this still an issue: I see `oclif-dev readme` in your `prepack` script?

https://github.com/james-hu/apig-swagger-ui/blob/master/package.json#L69

**Comment by james-hu** [comment]
@RasPhilCo Thanks for asking. I've made a workaround for the functionality that I need. So for now this is not blocking me. Probably the type of this issue can be changed to "feature request" because it seems the functionality is not intended to be there.

For my workaround, the usage in package.json is `"preversion": "./bin/run --update-readme.md && git add README.md"`, and the code in `run(...)` of `index.ts` is:
```
if (options.flags['update-readme.md']) {
      OclifUtils.injectHelpTextIntoReadmeMd(this);
      return;
}
```
Repo/example of the usage is here: https://github.com/james-hu/aws-serverless-dataflow
Code of the workaround is here: https://github.com/handy-common-utils/oclif-utils/blob/master/src/oclif-utils.ts

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
