### ISSUE TITLE
Support Deno

### ISSUE THREAD

**Issue by felipecrs** [oclif/oclif#432]
It would be awesome if OCLIF supports Deno. Fortunately, since OCLIF is written in TS, it should require very minor code changes.

## This covers

- [ ] Create a Deno entry-point for the Deno applications to import from
- [ ] Publish to deno.land/x

## Useful references

https://github.com/yargs/yargs/issues/1706
https://deno.land/manual/tools/script_installer

**Comment by sholtomaud** [comment]
Any update on this?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
