### ISSUE TITLE
default flag option with function is called before init hook

### ISSUE THREAD

**Issue by recheej** [oclif/oclif#434]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

What is the current behavior?
-----------------------------

```javascript
    static flags = {
        ...BaseCommand.flags,
        "flag-name": flags.string({
            required: true,
            description: ""
            default: () => {
                    // this function is called before init hook
                   return ""
           }
        })
    }
```

What is the expected behavior?
------------------------------
Init hook is supposed to be called before any command is found.

oclif 1.6.1. windows 10

**Comment by RasPhilCo** [comment]
Hmm, good catch.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
