### ISSUE TITLE
QUESTION: How do I use multi-char flags?

### ISSUE THREAD

**Issue by hsheikhali** [oclif/oclif#437]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature if this does not exist yet.\

What is the current behavior?
-----------------------------
Currently when I try to do the following:

`
  ['with-blobs']: flags.boolean({
    'char': 'wb',
    'default': true,
    description: 'Create a storage account with blobs, defaults to true',
  }),
`
And when I run the following command
` ./bin/bun command -wb=false `

it returns the following error:

Error: Unexpected argument: -wb=false

I expected this to work given that most command line interfaces accept 2 char and even 3 char flags.
------------------------------
Please mention your oclif and OS version.
oclif v1.16.1, OS: Manjaro Linux 20.1.1

**Comment by RasPhilCo** [comment]
Currently, we only parse single chars, ref https://github.com/oclif/parser/blob/69e17dd28a87588151f234437a68c6b3359d7a46/src/parse.ts#L88

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
