### ISSUE TITLE
Support for flag alias

### ISSUE THREAD

**Issue by ktalebian** [oclif/oclif#438]
## Do you want to request a *feature* or report a *bug*?

Feature. It would be useful to support aliases for flags. For example, I want to have

```bash
$ myCommand create --user "myName"
# or
$ myCommand create --add-user "myName"
```

To be the same flag, so have a `--user/add-user` as the same alias. 

## What is the current behavior?

You cannot create aliases for flags

**Comment by RasPhilCo** [comment]
Interesting idea

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by mdonnalley** [comment]
@ktalebian Support for this was added in [@oclif/core@1.17.0](https://github.com/oclif/core/releases/tag/1.17.0)
