### ISSUE TITLE
Default options outdated for multi

### ISSUE THREAD

**Issue by YizYah** [oclif/oclif#442]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Hmmm.  feature I guess.

What is the current behavior?
-----------------------------
Calling `multi --defaults` is still producing js! Considering that the interactive default is `ts`, that's probably not intended.

What is the expected behavior?
------------------------------
The defaults should at least include `ts`.

In general, I don't see an effective way to call the tool programmatically.  If someone could provide an example of a call with `--options`,  that would also be really helpful.  I have not been able to get it to work, and can't find it in the documentation.  I asked on the Spectrum community yesterday as well.

Please mention your oclif and OS version.
1.16.1

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
