### ISSUE TITLE
Compilation error on newly generated "multi" cli: TS6306

### ISSUE THREAD

**Issue by LassiterJ** [oclif/oclif#487]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Brand new "multi" cli gives compilation error:
 _" Error:(7, 5) TS6306: Referenced project '/Users/path/to/project' must have setting "composite": true."_

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Using the "multi" command generate a new cli.
2. Following the prompt I selected the following config options:

 npm package name: delete
? command bin name the CLI will export: delete
? description: delete
? author: Jonathan Lassiter @LassiterJ
? version: 0.0.0
? license: MIT
? Who is the GitHub owner of repository: (https://github.com/OWNER/repo) LassiterJ
? What is the GitHub name of repository: (https://github.com/owner/REPO) delete
? Select a package manager: yarn
? TypeScript: Yes
? Use eslint (linter for JavaScript and Typescript): Yes
? Use mocha (testing framework): Yes       ------------> This option generates the test folder with the tsconfig where the error occurs.
? Add CI service config: circleci

3. after new cli is generated, run the compiler and you should get the TS6306 error. 

What is the expected behavior?
------------------------------
No compile errors on new cli.

**Please mention your oclif and OS version.**
MacOs 11.1 BigSur
oclif/1.16.1 darwin-x64 node-v15.4.0
IDE: Webstorm 2020.3.1

Potentially related to #172

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
