### ISSUE TITLE
tsconfig "extends" entry not respected

### ISSUE THREAD

**Issue by aaroncraigongithub** [oclif/oclif#488]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Report a bug

What is the current behavior?
-----------------------------

Vanilla install (I did multi)
Rename `tsconfig.json` => `tsconfig.base.json`
Create `tsconfig.json` with the following content
```
{
  "extends": "tsconfig.base"
}
```

osclif will now not find commands.

What is the expected behavior?
------------------------------
The tsconfig parser should respect the "extends" option.

Using a `base` and `build` config with `tsconfig.json` simply extending `base` is a common way to have a shared base config with override options for builds.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by aaroncraigongithub** [comment]
Just a guess, but https://github.com/oclif/config/pull/225 seems to address this issue.

However, that PR is still unmerged after over a year, so not sure why this issue would be closed while that PR is unmerged.
