### ISSUE TITLE
document dependency injection best practices

### ISSUE THREAD

**Issue by jdxcode** [oclif/oclif#49]
perhaps this should be a new page on best practices for building CLIs

**Comment by wahtye** [comment]
Is there any update on this? What would you recommend? Constructor di doesnt seem too feasible with the way commands are structured

**Comment by jdxcode** [comment]
Not sure, we use proxyquire

**Comment by fzxt** [comment]
@jdxcode Can you provide a small example with how to do this?

**Comment by baksale** [comment]
I would like to see this example either.
Inside a command I want to have a 3rdPartServiceInstance

Inside a test I want to mock the instance methods calls.

Please share an example how we can do this and inject the required behaviour inside the test.

**Comment by from-nibly** [comment]
It would also be nice to be able to write mixins. I'm not a fan of inheritance based sharing, but if I have to do it I'd rather do it with mixins rather than a huge inheritance tree.

This coupled with something like proxyquire would probably give you a really powerful system of behavior sharing that would be compatible with only requiring stuff that you need to require for the one command, which I'll admit normal dependency injection does not lend itself to.

I tried thinking about how I could hack inversify into oclif and I realized that in order to respect that sort of tree shaking I'd have to write so much boilerplate with some sort of nested container tree where each dep gets it's own container or something.

mixins give you a close approximation to creating has-a relationships with inheritance.

As it stands, however, typescript doesn't support private or protected fields in mixins (which I really don't understand, I wish they'd just open that up and also support decorator based mixins). I even tried using the [alternate style of mixins](https://www.typescriptlang.org/docs/handbook/mixins.html#alternative-pattern)

With the normal way typescript complains about the Command class having protected fields with the following code.

```ts
import { Command } from "@oclif/core";

type Constructor<T> = (...args: any[]) => T;
type CommandConstructor = Constructor<Command>;

export const MyCommandMixin = <TBase extends CommandConstructor>(Base: TBase) => {
  return class MYCommandMixinBase {
  };
};
```

with the "alternate style" it works as long as none of your mixins also extend Command, which, would kind of be the point of having a bunch of command mixins...

There are some other libraries that could work like typescript-mix, but I ran into troubles with those as well.

Any effort in this space would be amazing, let me know if I should break this out as a separate issue.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
