### ISSUE TITLE
Using oclif with sentry

### ISSUE THREAD

**Issue by mick352** [oclif/oclif#497]
Do you want to request a *feature* or report a *bug*? Bug
-----------------------------------------------------

What is the current behavior?
-----------------------------
Sentry does not send data.

What is the expected behavior?
------------------------------
Sentry sends data

The following code works stand-alone and sends a message (node filename.js with "style": "module" in package.json)

    import * as Sentry from "@sentry/node";

    Sentry.init({
       dsn: "http://id@host/number",
    });

    Sentry.captureMessage('testing sentry 2');

Using the exact same in oclif's `run` function fails without any message (with import in top of file): 

    async run(): Promise<void> {
      const { flags } = this.parse(FileName)

      Sentry.init({
        dsn: 'http://id@host/number',
      })

      Sentry.captureMessage('testing sentry 3')
      // further code, runs

How can this be debugged /made to work (also at https://forum.sentry.io/t/using-sentry-with-oclif-for-cli/12815 )?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
