### ISSUE TITLE
Bare double dash arguments

### ISSUE THREAD

**Issue by isuvorov** [oclif/oclif#498]
Does oclif supports "bare double dash arguments"?

For example:
```sh
myCommand arg1 --flag2 val2 -- some other bare arguments as raw string
```

Example 2
```sh
npm run build -- --ext tsx
```

**Comment by metasean** [comment]
marckraw figured it out and explains how to do it here - https://github.com/oclif/oclif/issues/341#issuecomment-617234075

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
