### ISSUE TITLE
configuration utility

### ISSUE THREAD

**Issue by jdxcode** [oclif/oclif#50]
it would be nice if we had a standard way that oclif users could configure their CLI. Possibly this could be linked in with rc files of some sort. This may be better as a separate package.

**Comment by moulikcipherX** [comment]
@jdxcode can you please tell us more details about the issue..

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
