### ISSUE TITLE
Parse unspecified flags

### ISSUE THREAD

**Issue by gvjacob** [oclif/oclif#500]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
**bug** (unsure if intended or not)

What is the current behavior?
-----------------------------
Running CLI program with flags that are not defined in an oclif command throws `Error: Unexpected argument: --flag=flag`. I'm writing a program that takes in *any* user defined flags as a key value mapping, so they are not defined under `static flags` in my `Command` class. 

My Command configuration
```js
static flags = {
    version: flags.version({ char: 'v' }),
    verbose: flags.boolean({ char: 'V' }),
    help: flags.help({ char: 'h' }),
};

static args = [{ name: 'generator' }];
```

Running this line caused the error:
```sh
./bin/run generate --name=name
```

What is the expected behavior?
------------------------------
I would think that the `parse` method will still return values for these flags on top of the flags that are configured in `Command`. Even if the flags are not specifically configured, they should be parsed by oclif without any sort of validation that you would get from specified flags. 

If this is intended behavior, any way I can override this? One workaround I can think of is to set `strict = false` and parse the everything else with [commander](https://www.npmjs.com/package/commander).

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
