### ISSUE TITLE
oclif-plugin-spaced-command doesn't work with tests

### ISSUE THREAD

**Issue by kpayson** [oclif/oclif#502]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

**Comment by kpayson** [comment]
I set up the oclif-plugin-spaced-command plugin - which works as far as being able to replace colons with spaces but it is not compatible with the tests that use Nock.  It doesn't matter if I have 
.command(['foo:bar']) or .command(['foo bar']) or .command(['foo','bar']), when I try to run the test, I get the error telling me that it is not a command

**Comment by kpayson** [comment]
here is a demo of the issus https://github.com/kpayson/oclif-spaced-command-test-issue

`./bin/run users list`      *(this works)*

`npm run test`              *(to see errors)*

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
