### ISSUE TITLE
Autocomplete plugin throws error after npm update is run

### ISSUE THREAD

**Issue by rthangam** [oclif/oclif#516]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

1.)Add the autocomplete plugin to the oclif cli project using command yarn add @oclif/plugin-autocomplete
2.)Whenever you do npm update the following error throws when u run the cli

(node:6754) Error Plugin: xxxxx-oclif: could not find package.json with {
 type: 'core',
 root: '/xxxx/xxxx',
 name: '@oclif/plugin-autocomplete'
}
module: @oclif/config@1.15.1
task: loadPlugins
plugin: xxxxx-oclif
root: /xxxx/xxxx
See more details with DEBUG=*
isdtool % bin/run

What is the expected behavior?
------------------------------
Expected behaviour is not to get any errors.

OCLIF version 1.16.1

OS Version: Mac OS Catalina

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
