### ISSUE TITLE
How to perform `.node` file signing for notarization?

### ISSUE THREAD

**Issue by danthegoodman1** [oclif/oclif#522]
An issue I am having with macOS `.pkg` installer notarization is that the notarization rejects the `.pkg` file from `oclif` because the `.node` files in the various node packages are not signed. When trying to run the following to sign, I get this error.

```
bash-3.2# codesign -d -f -s "Developer ID Installer: #### (###)" node_modules/fsevents/fsevents.node
error: The specified item could not be found in the keychain.
```

What could be causing this, or what command should be used to sign the `.node` files? Does oclif support signing these nested binary files as well?

**Comment by danthegoodman1** [comment]
I've also verified the `Installer` and `Application` certs are in the system keychain, and have used the flag `--keychain /Library/Keychains/System.keychain`

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
