### ISSUE TITLE
Template replacement

### ISSUE THREAD

**Issue by metasean** [oclif/oclif#526]
This is primarily a question, but may turn out to be a feature request.

Is there an easy way to use custom templates?

For example, in the documentation for [creating a custom base class](https://oclif.io/docs/base_class) the example ends with the following `src/commands/myCommand.ts`:
```ts
// src/commands/mycommand.ts
import Command from '../base'

export class MyCommand extends Command {
  static flags = {
    ...Command.flags,
    extraflag: flags.string()
  }
  
  async run() {
    this.log('information', 'info')
    this.log('uh oh!', 'error')
  }
}
```

**_Is there a way to make that a template for subsequent runs of `oclif command <myNewCommand>`?_** E.g.
```ts
// src/templates/command.ts
import Command from '../base'

export default class <%- klass %> extends Command {
  static flags = {
    ...<%- klass %>.flags,
    extraflag: flags.string()
  }
  
  async run() {
    this.log('information', 'info')
    this.log('uh oh!', 'error')
  }
}
```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
