### ISSUE TITLE
how to create a login hook?

### ISSUE THREAD

**Issue by kpayson** [oclif/oclif#539]
most but not all of the commands for my cli require the user to be authenticated.  Currently, you need to first call the authenticate:login command and then call the other command (ex accounts:list)

I'd like to create a prerun hook that checks for an access token and if it doesn't exist or its expired call the login process.

I also want to command to support a --config flag to specify the enviornment that the command is execute against ex dev,qa,prod

So two questions:
1. how can flags be read from a hooks function
2. Is there a way to see a base class of the command being run so that I can only require the login if it inherits from an authenticated base class?

**Comment by maantje** [comment]
Hey @kpayson, I had the same question. But I did not solve it with hooks. I created a base command called AuthCommand and then check if authentication is setup correctly in the init function of that command. 

Not sure this is what you are looking for but I hope it helps. Below is the actual code I am using to do this.

AuthCommand: abstract class that extends the oclif/command with an init function that checks and prints an error where there is not token
```
import Command from '@oclif/command'
import { getConfig, bin } from './functions'
import { instructions, logger } from '@poppinss/cliui'
export default abstract class extends Command {
    async init() {
        const { token } = getConfig()

        if (!token) {
            logger.error('Setup auth before using this command')

            instructions()
                .add(`${bin()} ${logger.colors.cyan('auth [TOKEN]')}`)
                .render()

            this.exit()
        }
    }
}
```

And here is how I use it on the command that needs authentication, nothing changes pretty mutch. Just extending from AuthCommand instead of the default Command.

```
import { flags } from '@oclif/command'
import qlicnet from '../qlicnet-client'
import { bin } from '../functions'
import AuthCommand from '../auth-command'

export default class Get extends AuthCommand {
    static description = 'tell me who I am'

    static examples = [
        `${bin()} me`,
    ]

    static flags = {
        help: flags.help({ char: 'h' }),
    }

    async run() {
        const { data: user } = await qlicnet.get('/me')

        this.log(`You are ${user.display_name}!`)
    }
}
```
 
Now if I run the "me" command without token I get a message it is required to setup auth before being able to use this command.

![Screenshot 2021-03-20 at 21 34 52](https://user-images.githubusercontent.com/9058265/111884791-1c84e980-89c4-11eb-8a2e-696d110506e2.png)

**Comment by kpayson** [comment]
Yes.  I experimetned with hooks and also with class decorators but found that using the init() method in a base class was the best way to go.  In the iniit method I check that the token exisits and is not expired.  If the token is not good I can do the login process first.
