### ISSUE TITLE
Local binary ignored if CLI globally installed

### ISSUE THREAD

**Issue by DavidWells** [oclif/oclif#550]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Bug/feature

What is the current behavior?
-----------------------------

Running `./bin/run commandxyz` locally to test out an oclif CLI works great unless you have your CLI installed globally on your machine.

If you CLI is installed globally e.g. `npm i my-cli -g` running `./bin/run commandxyz` will execute the global binary instead of the local code.

This makes it challenging to iterate on the CLI locally without first uninstalling the global bin.

A way to "fix" this is to remove the `oclif.bin` property from the CLIs package.json. This will make the local code run instead of the local binary.

```diff
"oclif": {
  "commands": "./src/commands",
-  "bin": "share",
  "helpClass": "./src/utils/oclif/help-output",
  ...
},
```

What is the expected behavior?
------------------------------

When running against `./bin/run` it should only execute the local code. 

---

Thanks for the work on oclif! ❤️

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
