### ISSUE TITLE
Delay between pressing enter and command execution start

### ISSUE THREAD

**Issue by eduardnegru** [oclif/oclif#551]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug/Improvement

What is the current behavior?
-----------------------------
I am using Oclif 1.15.2, Ubuntu 19.10, Kernel 5.3.0-64-generic. There is a delay of about 1-2 seconds between the moment you press enter and the moment the first line of code in the run method is executed.

I have the following class:

```
export default class Show extends Command {

	static flags = {
		help: flags.help({char: 'h'}),
	}

	async run() {
		try {
			console.log("First")
			const {args, flags} = this.parse(Show)
                }
                catch(e) {
                }
        }
}
```
When I execute the show command, the first log from the class above is displayed after 1-2 seconds.

What is the expected behavior?
------------------------------
The delay should be a few milliseconds.

**Comment by amphro** [comment]
Are you doing a multi or single CLI? Most likely this is due to "dev" mode which is loading ts-node, which takes a lot more time.

Here are some dev mode stats using a single cli, which is what you are seeing. 

```bash
➜  oclifcli time ./bin/run
hello world from ./src/index.ts
./bin/run  2.15s user 0.14s system 172% cpu 1.328 total
```

Here is running off of the compile js code.

```bash
➜  oclifcli time ./bin/run
hello world from ./src/index.ts
./bin/run  0.11s user 0.03s system 105% cpu 0.131 total
```

Since this is dev time perf and is all consumed with ts-node, I'm going to close this out. If you think there is still an issue, please reopen or file a new issue more information and with benchmarks.

Thank you.
