### ISSUE TITLE
`oclif single` generates a `package.json` with `devDependencies` entry for `@types/node` not matching version of node used

### ISSUE THREAD

**Issue by rrthomas** [oclif/oclif#552]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Report a bug.

What is the current behavior?
-----------------------------
Run `npx single foo` and accept all default options.

Using `oclif` version 1.17.0 and `node` 14.16.0 installed with `nvm` on Ubuntu, the generated `package.json` has the following entry:

```json
  "devDependencies": {
    "@types/node": "^10.17.58",
  }
```

What is the expected behavior?
------------------------------
Add a dependency on the correct version for the version of node. This avoids problems such as https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44946

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
