### ISSUE TITLE
`yarn build` does not work for windows

### ISSUE THREAD

**Issue by Junkern** [oclif/oclif#56]
`yarn build` uses `rm` which is not available under windows

**Comment by jdxcode** [comment]
`rm` has been available on versions of windows I've been using

**Comment by Junkern** [comment]
Sorry for the late answer! I was using it on a Windows 10 with Powershell. Do you need more specific versions or informations?

**Comment by jdxcode** [comment]
That would be helpful if you have the versions

**Comment by AdrianoCahete** [comment]
PowerShell has `rm` as alias for [Remove-Item](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-6), but this alias don't accept another *unix parameters.

Maybe this is the problem.

**Comment by vadistic** [comment]
Hey, I've just discovered oclif - love it ❤️ 

To the topic: Quick workaround is to install `rimraf` and substitute in npm script `rm -rf lib` to `rimraf lib `.

In windows cmd shell (that I, and I suposse lot's of ppl is using instead of powershell) the `rm -rf` alias is `rmdir \s`  or `rd  \s`. Imo it's not that big of an Issue, but it would be good ux to make no-config oclif experience platform-agnostoic.

**Comment by jdxcode** [comment]
I wonder if it's something that I have installed on my machine that makes it work—maybe git for windows or something. I'd accept a pr to use `del-cli` or `rimraf` but only if `process.platform === 'win32'`. I'd like to keep the configuration as simple as possible on unix.
