### ISSUE TITLE
How to reuse `this.parse`?

### ISSUE THREAD

**Issue by marikaner** [oclif/oclif#566]
Question
-----------------------------------------------------

We are using oclif for our own CLI. We want to also make it available for programmatic use. As oclif already parses the flags it would be great to be able to reuse that functionality for programmatic use as well, e. g. when there are default values.

What we currently have is something like this:
```ts
class MyCommand extends Command {
  // ...

  async run(): Promise<void> {
    const parsed = this.parse(GenerateOpenApiClient);
    await executeMyCode(parsed.flags);
  }
}

// Shall be used programatically and should therefore also accept "unparsed" options
export function executeMyCode(options): Promise<void> {
  // reuse oclif "parsing" for flags 
}
```

What I actually need here isn't the parsing of argv, but the step after that: getting default values and parsing of the given values (e.g. when a `parse` function was specified for a flag). I would like to avoid implementing this manually (especially because it is already there).

Can I access this somehow?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
