### ISSUE TITLE
[Feature] please add support for GitHub actions as a CI

### ISSUE THREAD

**Issue by rluvaton** [oclif/oclif#574]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
A feature

Can you please add a GitHub Actions support

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by VictorioBerra** [comment]
Agree, at the very least this could be tagged as a good PR for beginners. Since the CI scripts are relatively simple.
