### ISSUE TITLE
More styling control for the cli-ux cli.table

### ISSUE THREAD

**Issue by Canuckaholic** [oclif/oclif#586]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
There doesn't appear to be a way to set the column widths/minWidths nor the cell padding.

What is the expected behavior?
------------------------------
It would be great to have a way to set the column widths (width, minWidth) and the table's cell padding to be able to give table content more breathing room.

cli-ux: ^5.5.1

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by sisou** [comment]
Found this issue because I also want a setting for `cellPadding`. I am displaying uniform data that has spaces in it, so one space separation between cells makes my table have virtually no columns. I would like to either increase the space, or define ` | ` as a column separator, for example.
![image](https://user-images.githubusercontent.com/1828163/189191214-a7462dac-f1bc-472a-a9f9-feac9750d18b.png)
