### ISSUE TITLE
Capitalize the default help command description

### ISSUE THREAD

**Issue by ericfledderman** [oclif/oclif#602]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Not quite a bug, but definitely not a feature.  The default behavior when creating a new command is that the description starts with a capital letter.  However, the default help command's description starts with a lowercase letter.  This has always sent my OCD through the roof.  Any chance we can adjust that?  The normal work around of creating a custom help command is a bit overkill for this usecase.

What is the current behavior?
-----------------------------
`
help   display help for...
`

What is the expected behavior?
------------------------------
`
help   Display help for...
`

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
