### ISSUE TITLE
How do create nested topic descriptions?

### ISSUE THREAD

**Issue by jhorst11** [oclif/oclif#65]
I would like to create a 2nd level nested command, something like:

`mycli apps:list`
`mycli apps:builds:create` 
`mycli apps:builds:list`

The documentation provides an example of how to modify the help for the `apps` topic, but I also want to modify the help topic for the `apps:builds` topic.

I was hoping to be able to do something like this in the package.json

```
"topics": {
      "apps": {
        "description": "manage your apps",
        "builds": {
             "description": "manage your builds for an app"
          }
      }
    }
```

Also as a suggestion, would it be possible to define an `index.ts` file in your command subdirectories where you could specify the topic's description as opposed to modifying the `package.json`?

**Comment by jdxcode** [comment]
it looks like this:

```js
"topics": {
    "apps": {
      "description": "manage your apps",
      "topics": {
        "builds": {
             "description": "manage your builds for an app"
        }
      }
    }
  }
}
```

**Comment by jhorst11** [comment]
thanks for the quick response @jdxcode unfortunately that still picks up to description of the first command in my apps/builds directory:

![image](https://user-images.githubusercontent.com/12836066/37729630-b9baf8a4-2cfa-11e8-8a69-12d4d26dc1f0.png)

**Comment by jdxcode** [comment]
might be a bug, looking into it. In regards to the `index.ts`. This would be technically possible but I'm assuming what you're doing here is trying to make the description dynamic (no?). Technically we could do this for topic descriptions, but it wouldn't work at all for command descriptions as we write this out to a manifest so we don't have to load every command when we run.

In general I've tried to move away from having files like this as I would have to require each of them from every plugin when the CLI first starts in order to load the help. For large CLIs, this gets slow pretty quickly unless you're careful not to require large dependencies.

**Comment by jdxcode** [comment]
oh I think I was thinking of an earlier code version, can you try this instead?

```js
"topics": {
    "apps": {
      "description": "manage your apps",
    },
    "apps:builds": {
         "description": "manage your builds for an app"
    }
  }
}
```

**Comment by jhorst11** [comment]
that did it! Thanks so much @jdxcode ! Great work on this!

**Comment by jdxcode** [comment]
I went ahead and put a little example in the README too
