### ISSUE TITLE
Multiple commands without runtime introspection (ncc, pkg, webpack, etc. compatibility)

### ISSUE THREAD

**Issue by LinusU** [oclif/oclif#653]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

feature

What is the current behavior?
-----------------------------

I'm trying to use [`ncc`](https://github.com/vercel/ncc) (which is basically an opinionated [Webpack](https://webpack.js.org) config) to package my cli tool into just a single file, for quicker startup and easier distribution. Unfortunately it seems like this doesn't really work since the `bin/run` file doesn't actually import the commands file, those are discovered at runtime.

Would it be possible to allow some form of syntax where I would pass in each command instead, e.g.

```javascript
#!/usr/bin/env node

require('@oclif/command').run([
  require('../src/commands/foo'),
  require('../src/commands/bar'),
  require('../src/commands/baz')
])
.then(require('@oclif/command/flush'))
.catch(require('@oclif/errors/handle'))
```

What is the expected behavior?
------------------------------
I expected all the code to end up in my bundle

**Comment by 0xdevalias** [comment]
Potentially related:

- https://github.com/oclif/oclif/issues/110
- https://github.com/oclif/oclif/issues/899

**Comment by sasha-firsov-bs** [comment]
The same solution would help with running oclif commands within terminal emulator SPA.
The `XTermJS` and `memfs` should potentially give enough for CLI be running in the browser.
🤔 perhaps `process` needs browser emulation too...

**Comment by moltar** [comment]
A few reasons why auto-discovery is a problem:

- No support for large projects that may have several unrelated internal CLIs, all in a single repo and `package.json`.
- Not possible to bundle the entire CLI into a single minified JS file and distribute it without `package.json`
- It is not explicit and magical. Violates the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by shumkov** [comment]
Hello! Any chance to have it in your roadmap?

**Comment by mdonnalley** [comment]
If anyone is still interested in this feature, I have a dev release of oclif/core that (hopefully) supports it. 

If you'd like to test it out:
1. Read the PR description on https://github.com/oclif/core/pull/945
2. Add `@oclif/core@dev` and `oclif@dev` to your project
3. Take a look at the example repo: https://github.com/oclif/plugin-test-esbuild

That example repo uses `esbuild` with minimal configuration changes to bundle the plugin into a single file. I have not tested this with other bundlers or with any unconventional configurations - any help in that regard would be appreciated.

Thanks!

**Comment by moltar** [comment]
Does it still need the package.json file with the bundle approach?

**Comment by mdonnalley** [comment]
>Does it still need the package.json file with the bundle approach?

Yes, it will still need a package.json since that's where all of oclif's configuration is put

**Comment by kanadgupta** [comment]
Hi @mdonnalley and co.! Thanks for all your work on this front and on oclif in general, very excited about it!

I've been playing around with this `dev` release and based on my understanding, even the new `explicit` strategy is only helpful in bundling the command/hook code itself, correct? So in addition to the command/hook bundle, oclif users will still need the following in order to actually run commands:
- `bin/run.js` (e.g., a file that invokes the `execute` function from `@oclif/core`) and all of its downstream dependencies, in order to actually run the commands
- `package.json` so the `bin/run.js` can properly load the barrel file that contains all of the commands/hooks/etc.

Right now [I have something _sort of_ working](https://github.com/readmeio/rdme/blob/793bbe62995023b03f3ed2ec5c55ee96622787dd/package.json#L120-L121) where it builds two JS bundles and still requires the `package.json` (which is technically a step in the right direction!), but my intended use case[^1] (and the use case described in this issue, based on my understanding) is different.

My goal[^1] is to be able to have a single JS file that contains _**everything**_ (i.e., all commands/hooks/plugins/etc. and any necessary `@oclif/core` code/configuration) so I can run the CLI without a `package.json` nor a `node_modules/` directory, like so:

```sh
node bundle.js
```

Is this a use case that will be addressed by https://github.com/oclif/core/pull/945? Please let me know if I'm missing something here, I'm still fairly new to this library. And happy to provide any further info on any of this if needed.

Thanks again!

[^1]: For context: [the CLI I maintain](https://github.com/readmeio/rdme) uses TypeScript and ESM and our CLI implementation is currently powered by a combination of [`command-line-args`](https://www.npmjs.com/package/command-line-args) and [`command-line-usage`](https://www.npmjs.com/package/command-line-usage), and we use a combination of [Rollup](https://rollupjs.org/) (which is very similar to esbuild) and [`pkg`](https://www.npmjs.com/package/pkg) to bundle the CLI into a single file executable. I've been investigating a migration over to oclif (for many good reasons!) but it doesn't seem like the TypeScript + ESM usage of oclif plays nicely with `pkg`.

**Comment by mdonnalley** [comment]
@kanadgupta 

> even the new explicit strategy is only helpful in bundling the command/hook code itself, correct?

Yes, the primary goal of the `explicit` strategy is to support bundling (there are, however, other benefits that people might find useful, like being able to dynamically create or modify commands at runtime). But using the `explicit` doesn't automatically make your CLI bundle-able. There are still a few other things you need to do to actually get there. Take a look at the discussion in https://github.com/oclif/core/issues/965. Isaac has a repo that might be a useful example for you.

> My goal is to be able to have a single JS file that contains everything (i.e., all commands/hooks/plugins/etc. and any necessary @oclif/core code/configuration) so I can run the CLI without a package.json nor a node_modules/ directory

Running without `node_modules` directory will be possible (take a look at [this comment](https://github.com/oclif/core/issues/965#issuecomment-1967294760)). As for the package.json, I'll need to think through a few options there

**Comment by mdonnalley** [comment]
@kanadgupta After exploring some options, we've decided that we're not going to support your use case (i.e. a single file CLI with no package.json or bin/run.js).

The primary issue is that the installers created using `oclif pack` rely on having a `bin` directory with an executable named `run` or `run.js`. We'd have to refactor that (and figure out how to introduce that change without breaking users of any oclif CLI) and then figure out how to deal with the downstream affects of that in @oclif/plugin-update. To be completely honest, it's just more risk, time, and effort than we're willing to put in at the moment.

So if people want to bundle their CLI, the bundle must include a package.json and a `bin/run.js` (and any other relevant files like an `oclif.manfiest.json`)

Once all the work is merged, I'll update oclif.io with a section on how to bundle an oclif CLI and the limitations/downsides of doing so.

**Comment by kanadgupta** [comment]
Appreciate your investigation into this @mdonnalley! 

Also taking a look at https://github.com/oclif/core/issues/965 — it looks like the key thing here is the usage of `run` function from `@oclif/core`. Mind shedding some light on the difference between `run` and `execute`? I'm not seeing much in the docs on this. Thanks again!

**Comment by mdonnalley** [comment]
`execute` is just a small convenience wrapper around `run`

If you take a look [here](https://github.com/oclif/core/blob/main/src/execute.ts#L47), you'll see that it's simply:
- setting NODE_ENV to `development`,  if in development
- setting `settings.debug`, if in development
- calling `run` then `flush`
- error handling with `handle`
