### ISSUE TITLE
"did you mean" for flag names

### ISSUE THREAD

**Issue by jdxcode** [oclif/oclif#66]
using the [not-found plugin](https://github.com/oclif/plugin-not-found) we show friendly "did you mean" messages when a user mistypes a command. It would be nice if this also showed "did you mean" messages for mistyped flags.

Example:

```js
import {Command, flags} from '@oclif/command'

export class extends Command {
  static flags = {
    'my-flag': flags.string()
  }

  async run() {}
}
```

Usage:

```sh-session
$ ./bin/run --myflag
Did you mean --my-flag?
```

This logic would probably have to go into the [parser](https://github.com/oclif/parser).

**Comment by moulikcipherX** [comment]
I think this issue has been taken care of so it must be closed.

**Comment by jdxcode** [comment]
No flag names do not have this support

**Comment by moulikcipherX** [comment]
Hello @jdxcode 
I didn't find any documentation on plugin-not-found. Can you help me with it?

**Comment by JesseVermeulen123** [comment]
There is a hook for [CommandNotFound](https://github.com/oclif/config/blob/master/src/hooks.ts#L37), but not for flag not found?

So unless that's raised for a wrong flag, we wouldn't be able to do what [plugin-not-found](https://github.com/oclif/plugin-not-found/blob/master/src/index.ts#L7) does

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
