### ISSUE TITLE
Where to put markdown, json, and other static data files?

### ISSUE THREAD

**Issue by viglucci** [oclif/oclif#753]
Question
-----------------------------------------------------

The CLI I am working on requires some static JSON, as well as some markdown files to be included in the CLI source code. Is there anywhere special these static files need to exist so that the files will be included in the packed version of the CLI?

My first thought is to include the files in `src/resources/`, or a similar folder.

Any thoughts? Thanks.

**Comment by mdonnalley** [comment]
@viglucci we like to put our static files under `/messages` folder that's at the root of the project. For example, https://github.com/salesforcecli/plugin-env/tree/main/messages

If you go that route, just be sure to also include `messages` in the `files` property of the package.json so that it gets published to npm, e.g. https://github.com/salesforcecli/plugin-env/blob/main/package.json#L64

That being said, there is no hard and fast rule that you must follow. You can put your static files where ever you would like.

**Comment by viglucci** [comment]
Thanks for the quick response @mdonnalley. I'll give that recommendation a try. I wasn't sure if adding the directory to `files/` would be sufficient, as for our CLI we don't publish to NPM as it's a internal tool.
