### ISSUE TITLE
warn if flags conflict

### ISSUE THREAD

**Issue by jdxcode** [oclif/oclif#79]
for instance, if 2 flags have the same short char

**Comment by shadxx7** [comment]
Hey,

Can I work on this issue?

**Comment by jdxcode** [comment]
of course

**Comment by shadxx7** [comment]
Hey so, I wanted to clarify somethings, first of all I currently am looking into the oclif/parser/src/flags.ts and oclif/parser/src/parse.ts files right now, am I going in the right direction? Next, just confirming the feature we are trying to add is to give a warning if a developer of a CLI made using oclif defined 2 or more conflicting flags, right?

**Comment by jdxcode** [comment]
sounds right to me

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
