### ISSUE TITLE
Add husky with lint-staged when user generate the project using `npx oclif generate`

### ISSUE THREAD

**Issue by thelovekesh** [oclif/oclif#850]
Do you want to request a *feature* or report a *bug*?
Feature: Add husky with lint-staged at the time of the project is generated using the `npx oclif generate`

Since the project is already shipped with eslint configured, lint-staged with husky can be configured easily. It can help to ship better and healthier code that follows eslint standards.

**Comment by mdonnalley** [comment]
The generator is intended to be un-opinionated about things like that. I agree that husky and lint-staged are great additions to any project but as soon as we include them we'll get an issue with someone stating that the generator shouldn't have those by default because they want to use a different set of tools. Can't really win with these kinds of things.
