### ISSUE TITLE
Oclif v2 doesn't work with yarn workspaces

### ISSUE THREAD

**Issue by horaklukas** [oclif/oclif#901]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
I migrated our CLI to oclif v2 according to the migration guide.
The repository is [monorepo](](https://github.com/AckeeCZ/lokse)) powered by yarn workspaces, but after migration example running of CLI stopped working

I took an official oclif hello world repository and converted it to similar repository our CLI has so you can test it on it. It's basically the example CLI just moved to `packages/mynewcli` subfolder and added `example` folder with package.json having the CLI as a dependency.

https://github.com/horaklukas/oclif-hello-world

In previous Oclif version when I run of the commands below

```sh
yarn workspaces example oex hello world
cd example; yarn oex hello world
./packages/mynewcli/bin/run hello world
```
 it always fail with message
> MODULE_NOT_FOUND] ModuleLoadError Plugin: oclif-hello-world: [MODULE_NOT_FOUND] require failed to load /oclif-hello-world/packages/mynewcli/src/commands/hello/world

When I turn on logs I can see it tries to load commands from `src` instead of `dist` folder 🤔 
> Cannot find module '/private/tmp/oclif-hello-world/packages/mynewcli/src/commands/hello/world'

So my guess is there is some weird relative module resolution...

What is the expected behavior?
------------------------------
Used oclif v2

Working CLI in yarn workspaces environment as it worked well with oclif v1

**Comment by 0xdevalias** [comment]
I was intrigued to take a naive look into this and try and figure out if I could see why it might be getting the wrong path/etc.

Deepdive context:

- https://github.com/horaklukas/oclif-hello-world/blob/main/packages/mynewcli/bin/run#L5
  - requires `@oclif/core`, then calls `oclif.run()`
- https://github.com/oclif/core/blob/main/src/main.ts#L35-L79
  - `export async function run(`
  - find and run command: https://github.com/oclif/core/blob/main/src/main.ts#L63-L72
    - `const cmd = config.findCommand(id)`
- https://github.com/oclif/core/blob/main/src/config/config.ts#L372-L377
  - `findCommand(id: string, opts: { must?: boolean } = {}): Command.Loadable | undefined {`
  - Looking at where the `Config` is loaded: https://github.com/oclif/core/blob/main/src/config/config.ts#L146-L148
    - `const plugin = new Plugin.Plugin({root: this.options.root})`
    - `await plugin.load()`
      - https://github.com/oclif/core/blob/main/src/config/plugin.ts#L135-L164
  - Looking at the definition of `root` in the `Plugin` interface: https://github.com/oclif/core/blob/main/src/interfaces/plugin.ts#L53-L56
    - `base path of plugin`
  - `Config`'s `this.options` is passed in from the original `run` command's 2nd parameter: https://github.com/oclif/core/blob/main/src/main.ts#L35-L42
    - And uses the `Config.load` static function: https://github.com/oclif/core/blob/main/src/config/config.ts#L132-L143
      - Which seems to suggest it can handle having a `file://` path (see `fileURLToPath`), plain string (in which case it wraps it as `{root: opts}`), or object that conforms to `isConfig` passed to it.
      
Basically.. after all of that digging/looking to figure how things work, my thought/theory/question is whether setting that `root` path in the config to the run command would allow it to work correctly.

---

**Edit:** Additional context/thoughts.

- In `Plugin`, there is `get commandsDir()`: https://github.com/oclif/core/blob/main/src/config/plugin.ts#L170-L172
- Which calls `tsPath(this.root, this.pjson.oclif.commands)`
- `tsPath` is defined in https://github.com/oclif/core/blob/main/src/config/ts-node.ts#L37-L79, and notes the following in comments:
  - > convert a path from the compiled ./lib files to the ./src typescript source
  - > this is for developing typescript plugins/CLIs
  - > if there is a tsconfig and the original sources exist, it attempts to require ts-

So my guess is this is the source of the "it seems to be trying to load from `src/` rather than `lib/`; though I haven't yet looked any deeper into the specifics of why this part of things is getting called.

- `commandsDir` is called from `findCommand` https://github.com/oclif/core/blob/main/src/config/plugin.ts#L206-L236
  - `findCommand` does some path manipulation, then calls `ModuleLoader`
    - `const p = path.join(this.pjson.oclif.commands as string, ...id.split(':'))`
    - `const {isESM, module, filePath} = await ModuleLoader.loadWithData(this, p)`
  - And if there is a `MODULE_NOT_FOUND` error, it re-throws the error

**Comment by 0xdevalias** [comment]
Just tried cloning your repo to see if I could reproduce the error you're seeing, but it seemed to work for me when running `yarn workspace example oex hello`. Is this still an issue?

```
⇒  git clone git@github.com:horaklukas/oclif-hello-world.git

..snip..

⇒  cd oclif-hello-world

⇒  yarn install
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-503d203f-3764-4662-9c29-8e8a261226d4 > oclif-hello-world > oclif > yeoman-environment@3.9.1" has unmet peer dependency "mem-fs@^1.2.0 || ^2.0.0".
warning "workspace-aggregator-503d203f-3764-4662-9c29-8e8a261226d4 > oclif-hello-world > oclif > yeoman-environment@3.9.1" has unmet peer dependency "mem-fs-editor@^8.1.2 || ^9.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 10.47s.
```

```
⇒  yarn workspace example oex hello world
yarn workspace v1.22.19
yarn run v1.22.19
$ /Users/devalias/dev/tmp/oclif-hello-world/node_modules/.bin/oex hello world
 ›   Error: command hello:world not found
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 2
Command: /Users/devalias/.nodenv/versions/16.15.1/bin/node
Arguments: /usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js oex hello world
Directory: /Users/devalias/dev/tmp/oclif-hello-world/example
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

```
⇒  yarn workspace example oex hello
yarn workspace v1.22.19
yarn run v1.22.19
$ /Users/devalias/dev/tmp/oclif-hello-world/node_modules/.bin/oex hello
Say hello to the world and others

USAGE
  $ oex hello COMMAND
```

**Comment by alanquigley-toast** [comment]
Adding `"skipLibCheck": true` to the `tsconfig.json` resolved the issue in my case. 
Lerna & yarn 1.x workspaces project.

**Comment by horaklukas** [comment]
@0xdevalias Don't know how you did achive it 😅  I cloned the fresh repo, run same `yarn install` & `yarn workspace example oex hello`  but still getting the MODULE_NOT_FOUND error. Didn't you forget some local modifications from your packages exploration?

Also "skibLibCheck": true didn't solve the problem..

**Comment by 0xdevalias** [comment]
> Don't know how you did achive it 😅 I cloned the fresh repo, run same `yarn install` & `yarn workspace example oex hello` but still getting the MODULE_NOT_FOUND error. Didn't you forget some local modifications from your packages exploration?

@horaklukas What version of `yarn` are you using? Definitely didn't forget any local packages, I just followed the exact same steps from above ([Ref](https://github.com/oclif/oclif/issues/901#issuecomment-1206213236)) and it worked again. This was from a completely fresh setup, new clone, etc.

**Comment by aaronmgdr** [comment]
had a similar issue. 

yarn 3, typescript 5, lastest oclif packages, + jest + ts-jest, + ts-node. where deep inside of oclif/core  async import of tsconfck module would cause node to completely crash. I solved by setting `global.oclif = { tsnodeEnabled: false }` in jest global setup

**Comment by mdonnalley** [comment]
I can't reproduce this either - so I'm going to close. Please feel free to open a new issue if you're still experiencing this
