### ISSUE TITLE
Oclif CLIs can be generated with NX generator

### ISSUE THREAD

**Issue by liebsoer** [oclif/oclif#935]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
feature

What is the current behavior?
-----------------------------
Not possible to easily integrate oclif clis into NX workspaces

What is the desired behavior?
------------------------------
As a developer, I want to generate new CLIs with a NX generator, so that I have a consistent tooling experience.

Currently it's not easily possible to add an Oclif CLI to the NX (https://nx.dev) workspace as an app. The only feasible way I found is described here: https://dev.to/digikare/oclif-on-nx-monorepo-33bo
As I love to use NX workspaces for my mono repositories, I would really love to have an officially supported generator and executors to use with nx.

**Comment by 0xdevalias** [comment]
> Not possible to easily integrate oclif clis into NX workspaces

@liebsoer What are the current issues with integrating oclif CLIs into NX workspaces in your experience? This is something I have recently been looking into for my own project needs, and was considering trying to put together an nx plugin to simplify  the process; but i'm not aware of what the current issues/complexities are specifically.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
