### ISSUE TITLE
Add oclif to existing project

### ISSUE THREAD

**Issue by toymachiner62** [oclif/oclif#999]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Request a feature (unless it already exists)

What is the current behavior?
-----------------------------
I can't run `oclif generate myprojec` and point to my existing project and have just the necessary files added there.

What is the expected behavior?
------------------------------
Essentially I want a way to add oclif to an existing project

**Comment by joshcanhelp** [comment]
I can take a crack at this one. From poking around and trying things out, it seems like the two things that need to be done, at a minimum, are:

- Install `@oclif/core` if not
- Add the `./bin/*` files. Because those are different between the [CJS](https://github.com/oclif/hello-world/tree/main/bin) and [ESM](https://github.com/oclif/hello-world-esm/tree/main/bin) examples, we'll need to ask the user what module type they're using and maybe try to [auto-detect](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling).
- Add the following to `package.json`:

```js
{
	// ...
	"oclif": {
		"commands": "./dist/commands"
	}
}
```

Questions:

- Do we need to do anything else in this command? From my testing, this was the bare minimum to get `./bin/run.js command` working.
- Are there any other config values we should be setting in `package.json`?

CC @mdonnalley

**Comment by mdonnalley** [comment]
> we'll need to ask the user what module type they're using and maybe try to [auto-detect](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling).

I think detecting the module type would be the best user experience here

> Are there any other config values we should be setting in package.json?

`oclif generate` will also set the `bin` which gets set in `oclif.bin` and in `bin`. It's not necessary for running `bin/run.js` but will be necessary once it's published. 

If the package.json already has a `bin` you could use that to populate `oclif.bin`
